import type { Dict, Trade } from "./fr";

export const de: Dict = {
  meta: {
    title: "Biltov — Der Sprach- und Rechnungsassistent für Bauhandwerker in Belgien",
    description: "Diktieren Sie Ihre Angebote auf der Baustelle auf Deutsch, Französisch oder Niederländisch. Biltov wendet die belgische MwSt. an, erstellt Ihre Peppol-Rechnungen und hilft beim Kassieren.",
  },
  nav: {
    features: "Funktionen",
    videos: "Videos",
    trades: "Gewerke",
    pricing: "Preis",
    about: "Über uns",
    roi: "Rechner",
    cta: "5 Tage kostenlos testen",
    dashboard: "Mein Bereich",
    language: "Sprache",
    openMenu: "Menü öffnen",
    lightMode: "Tagmodus",
    darkMode: "Nachtmodus",
    closeMenu: "Menü schließen",
  },
  hero: {
    badge: "Für Handwerker in Belgien · DE · FR · NL",
    titleA: "Stift weglegen.",
    titleHighlight: "Diktieren.",
    titleB: "Biltov erledigt den Papierkram.",
    subtitle:
      "Diktieren Sie das Angebot auf der Baustelle: Biltov findet Ihre Preise, wendet den richtigen belgischen MwSt.-Satz an, gestaltet es in Ihren Farben und hilft Ihnen, es unterschreiben zu lassen, zu fakturieren und zu kassieren.",
    ctaPrimary: "Diktat testen",
    ctaSecondary: "Demo ansehen",
    reassurance: ["Belgische MwSt. 6 / 12 / 21 % und Umkehrung", "Peppol-BIS-3.0-Rechnungen", "5 Tage gratis, ohne Karte"],
    stats: [
      { value: "30 s", label: "um ein Angebot zu diktieren" },
      { value: "3", label: "Sprachen: DE, FR, NL" },
      { value: "+++", label: "strukturierte Mitteilung auf jeder Rechnung" },
    ],
    canvasHint: "Bewegen Sie die Maus, um die Baustelle zu drehen",
    scroll: "Scrollen",
  },
  trades: {
    eyebrow: "Ihr Gewerk",
    title: "Biltov spricht Ihr Gewerk.",
    subtitle: "Wählen Sie Ihr Gewerk: Wortschatz und Startkatalog passen sich an. Ihre Preise bleiben Ihre Preise.",
    labels: {
      dictation: "Sie diktieren",
      generated: "Biltov erstellt",
      supplies: "Startkatalog",
      jargon: "Verstandene Fachbegriffe",
      vat: "Angewandte MwSt.",
      total: "Gesamt netto",
      designation: "Bezeichnung",
      qty: "Menge",
      price: "EP netto",
    },
    list: [
      {
        id: "plombier",
        name: "Installateur (Sanitär / Heizung)",
        voice: "Für Frau Schmitz in Eupen, Austausch des elektrischen Boilers 200 Liter, Sicherheitsgruppe, Mehrschichtverbinder und 3 Stunden Arbeitszeit.",
        lines: [
          { label: "Elektroboiler 200 L senkrecht", qty: 1, unit: "u", price: 489 },
          { label: "Sicherheitsgruppe + Siphon", qty: 1, unit: "u", price: 42 },
          { label: "Mehrschichtverbinder Ø16 + Schellen", qty: 1, unit: "lot", price: 36 },
          { label: "Arbeitszeit Installateur", qty: 3, unit: "h", price: 55 },
        ],
        supplies: ["Mehrschichtrohr Ø16 / Ø20", "Messingfittings", "Boiler", "Mischbatterien", "Siphons", "Kugelhähne"],
        jargon: ["Boiler", "Sicherheitsgruppe", "Mehrschichtrohr", "Rückschlagventil", "Ausdehnungsgefäß"],
        vat: "6 % (Privatwohnung älter als 10 Jahre)",
      },
      {
        id: "electricien",
        name: "Elektriker",
        voice: "Für Herrn Lambertz in Sankt Vith, Austausch des Verteilers, 2 FI-Schalter 30 Milliampere, 12 Sicherungsautomaten, 6 Steckdosen und 5 Stunden Arbeitszeit.",
        lines: [
          { label: "Unterverteiler 3 Reihen", qty: 1, unit: "u", price: 128 },
          { label: "FI-Schalter 40 A 30 mA Typ A", qty: 2, unit: "u", price: 74 },
          { label: "Sicherungsautomat 2-polig 16 A", qty: 12, unit: "u", price: 11.5 },
          { label: "Unterputzsteckdose + Montage", qty: 6, unit: "u", price: 38 },
        ],
        supplies: ["Sicherungsautomaten", "FI-Schalter 30 mA", "Leerrohr", "Kabel XVB / VOB", "Unterputzdosen", "Phasenschienen"],
        jargon: ["AREI/RGIE", "Konformitätsprüfung", "FI-Schalter", "Unterverteiler", "Einliniendiagramm"],
        vat: "6 % (Privatwohnung älter als 10 Jahre)",
      },
      {
        id: "peintre",
        name: "Maler",
        voice: "Für Familie Kessler in Kelmis, Abwaschen, Spachteln, Grundierung und zwei Anstriche weißer Latex auf 38 m² Wänden, Decke 14 m² matt.",
        lines: [
          { label: "Abwaschen + Spachteln + Schleifen Wände", qty: 38, unit: "m²", price: 6 },
          { label: "Acrylgrundierung", qty: 38, unit: "m²", price: 4.5 },
          { label: "Weißer Latex 2 Anstriche", qty: 38, unit: "m²", price: 14 },
          { label: "Decke Mattfarbe 2 Anstriche", qty: 14, unit: "m²", price: 17 },
        ],
        supplies: ["Latex / Acryl", "Glättspachtel", "Fugenband", "Rollen", "Abdeckplanen", "Abklebeband"],
        jargon: ["Latex", "Tiefgrund", "Spachteln", "Zwischenschliff", "tiefmatt"],
        vat: "6 % (Privatwohnung älter als 10 Jahre)",
      },
      {
        id: "macon",
        name: "Maurer",
        voice: "Für Herrn Mertens in Raeren, Terrassenplatte 25 m² bei einem Neubau, 12 Zentimeter, Bewehrungsmatte, 20 cm Schotter und Schalung.",
        lines: [
          { label: "Erdarbeiten + Schotter 20 cm", qty: 25, unit: "m²", price: 28 },
          { label: "Bewehrungsmatte", qty: 25, unit: "m²", price: 7.5 },
          { label: "Beton C25/30 12 cm gegossen", qty: 3, unit: "m³", price: 165 },
          { label: "Randschalung", qty: 20, unit: "ml", price: 18 },
        ],
        supplies: ["Beton C25/30", "Betonsteine", "Bewehrungsmatten", "Betonstahl", "Mörtel", "PE-Folie"],
        jargon: ["Schotter", "Hohldielen", "Estrich", "Bewehrung", "Sturz"],
        vat: "21 % (Neubau)",
      },
      {
        id: "menuisier",
        name: "Schreiner",
        voice: "Für Frau Hilgers in Bütgenbach, Einbau von 3 PVC-Fenstern mit Doppelverglasung 120 mal 135, Ausbau der alten Holzfenster, Verkleidung und Fugen.",
        lines: [
          { label: "PVC-Fenster 2-flügelig 120×135 Uw 1,3", qty: 3, unit: "u", price: 540 },
          { label: "Ausbau bestehender Holzfenster", qty: 3, unit: "u", price: 65 },
          { label: "Verkleidung + PVC-Abdeckleisten", qty: 3, unit: "u", price: 48 },
          { label: "Dichtstoff + PU-Schaum + Kompriband", qty: 1, unit: "lot", price: 45 },
        ],
        supplies: ["PVC- / Alufenster", "Kompriband", "PU-Schaum", "Abdeckleisten", "Schrauben", "Beschläge"],
        jargon: ["Blendrahmen", "Flügel", "Renovierungsrahmen", "Uw", "Kompriband"],
        vat: "6 % (Privatwohnung älter als 10 Jahre)",
      },
      {
        id: "paysagiste",
        name: "Garten- und Landschaftsbauer",
        voice: "Für die Villa Lambertz in Eupen, 120 m² Rollrasen, 8 m³ Mutterboden, 25 m² Terrassenpflaster und die monatliche Heckenpflege.",
        lines: [
          { label: "Gesiebter Mutterboden geliefert und verteilt", qty: 8, unit: "m³", price: 48 },
          { label: "Rollrasen verlegt", qty: 120, unit: "m²", price: 11.5 },
          { label: "Terrassenpflaster auf Schotter verlegt", qty: 25, unit: "m²", price: 78 },
          { label: "Heckenschnitt (monatliche Pflege)", qty: 3, unit: "h", price: 45 },
        ],
        supplies: ["Mutterboden", "Rollrasen", "Mulch", "Pflaster und Randsteine", "Schotter", "Pflanzen"],
        jargon: ["Schotter", "Mulchen", "Vertikutieren", "Randstein", "Drainage"],
        vat: "21 % (Garten: vom 6-%-Satz ausgeschlossen)",
      },
    ] as Trade[],
  },
  features: {
    eyebrow: "Funktionen",
    title: "Das ganze Büro in Ihrer Tasche.",
    subtitle: "Gemacht für die Baustelle und die belgischen Regeln. Ein Abonnement, alles inklusive.",
    voice: {
      title: "Diktat → Angebot",
      desc: "Sprechen Sie wie auf der Baustelle. Biltov erkennt Mengen, Einheiten und Preise, findet die Artikel aus Ihrem Katalog und erstellt ein unterschriftsbereites PDF-Angebot.",
      listening: "Hört zu…",
      thinking: "Kalkuliert…",
      ready: "PDF fertig",
      transcript: "« Bad bei Kessler, 18 m² Wandfliesen, Einbau einer flachen Duschtasse, 2 Tage Arbeitszeit »",
      pdfLines: ["Wandfliesen 30×60 — 18 m²", "Flache Duschtasse 90×120", "Arbeitszeit Fliesenleger — 2 T"],
      quote: "ANGEBOT D-2026-0142",
    },
    channels: {
      title: "Versand per E-Mail, WhatsApp, SMS",
      desc: "Die Nachricht ist vorbereitet, in der Sprache des Kunden, mit dem PDF. Zwischen Unternehmen wird die Rechnung im Peppol-Format erstellt.",
      email: "E-Mail",
      whatsapp: "WhatsApp",
      sms: "SMS",
      send: "Angebot senden",
      sending: "Senden…",
      delivered: "Gesendet",
      reset: "Neu starten",
      none: "Aktivieren Sie mindestens einen Kanal",
    },
    reminders: {
      title: "Mahnungen nach belgischen Regeln",
      desc: "Biltov bereitet jede Mahnung zum richtigen Zeitpunkt vor: Buch XIX für Privatkunden (1. Erinnerung kostenlos, 14 Tage Frist), Gesetz vom 2. August 2002 für Geschäftskunden.",
      steps: [
        { day: "1", title: "1. Erinnerung (kostenlos)", msg: "Guten Tag Herr Kessler, sofern kein Irrtum vorliegt, ist die Rechnung F-2026-0088 (1 240 €) noch offen. Bitte zahlen Sie sie innerhalb von 14 Tagen, ohne Kosten. Mitteilung: +++090/9337/55493+++" },
        { day: "2", title: "Mahnung", msg: "Guten Tag Herr Kessler, trotz unserer Erinnerung ist die Rechnung F-2026-0088 weiterhin unbezahlt. Es sind nun Kosten und Zinsen gemäß Buch XIX des Wirtschaftsgesetzbuches geschuldet." },
        { day: "3", title: "Inverzugsetzung", msg: "Inverzugsetzung zur Zahlung der Rechnung F-2026-0088, einschließlich Kosten und Zinsen, innerhalb von 8 Tagen. Andernfalls wird die Akte dem Inkasso übergeben." },
      ],
      paid: "Bezahlt — Mahnungen gestoppt",
      markPaid: "Zahlung simulieren",
    },
    photo: {
      title: "Fotos & Marge der Baustelle",
      desc: "Vorher-/Nachher-Fotos mit Zeitstempel in der Baustellenakte. Fotografieren Sie Ihre Belege: Biltov liest den Betrag und berechnet die Marge.",
      before: "Vorher",
      after: "Nachher",
      scan: "Beleg scannen",
      scanning: "Lesen…",
      receipt: "Händlerbeleg",
      items: [
        { label: "Fliesenkleber C2 × 4", value: 86.4 },
        { label: "Fugenkreuze 3 mm", value: 7.9 },
        { label: "Fugenmörtel grau 5 kg", value: 18.5 },
      ],
      billed: "An den Kunden fakturiert",
      costs: "Einkäufe",
      margin: "Marge der Baustelle",
    },
    brand: {
      title: "Ihre Dokumente, in Ihrem Stil",
      desc: "Ihr Logo, Ihre Farben, Ihre IBAN und Ihre Unternehmensnummer. Die belgische MwSt. wird Zeile für Zeile berechnet.",
      upload: "Logo importieren",
      color: "Farbe",
      country: "MwSt.-Satz",
      iban: "IBAN",
      company: "Kessler Renovierung GmbH",
      preview: "PDF-Vorschau",
      subtotal: "Gesamt netto",
      vat: "MwSt.",
      total: "Gesamt brutto",
    },
  },
  demo: {
    eyebrow: "Live-Demo",
    title: "Sagen Sie es. Sehen Sie, wie sich das Angebot füllt.",
    subtitle: "Wählen Sie einen Beispielsatz, tippen Sie Ihren eigenen oder nutzen Sie Ihr Mikrofon: Das Angebot entsteht Zeile für Zeile.",
    examples: [
      "Für Frau Schmitz, 24 m² Eichenparkett zu 45 Euro, 12 lfm Sockelleisten zu 9 Euro und 6 Stunden Arbeitszeit zu 50 Euro",
      "Für Herrn Lambertz, 3 Steckdosen zu 38 Euro, einen Verteiler zu 180 Euro und 4 Stunden Arbeitszeit zu 55 Euro",
      "Für Horizon GmbH, 60 m² Wandanstrich zu 22 Euro und 18 m² Decke zu 25 Euro",
    ],
    placeholder: "Z. B.: Für Herrn Dubois, 10 m² Fliesen zu 40 Euro und 5 Stunden zu 50 Euro",
    simulate: "Diktat starten",
    mic: "Mit Mikrofon diktieren",
    stop: "Stoppen",
    micUnsupported: "Mikrofon in diesem Browser nicht verfügbar — nutzen Sie ein Beispiel.",
    listening: "Biltov hört zu…",
    reset: "Löschen",
    live: "Live-Transkription",
    pdf: {
      quote: "ANGEBOT",
      number: "D-2026-",
      client: "Kunde",
      clientUnknown: "Kunde offen",
      date: "Datum",
      designation: "Bezeichnung",
      qty: "Menge",
      unitPrice: "EP netto",
      total: "Gesamt netto",
      subtotal: "Gesamt netto",
      vat: "MwSt. 6 %",
      vatRate: 6,
      totalTTC: "Gesamt brutto",
      validity: "Angebot 30 Tage gültig · « Gelesen und genehmigt »:",
      empty: "Die Zeilen erscheinen hier während des Diktats…",
      labour: "Arbeitszeit",
    },
  },
  roi: {
    eyebrow: "Rechner",
    title: "Wie viel Zeit gewinnen Sie zurück?",
    subtitle: "Stellen Sie die Regler auf Ihre Tätigkeit ein. Die Berechnung ist bewusst vorsichtig.",
    quotes: "Angebote und Rechnungen pro Monat",
    minutes: "Aktuelle Zeit pro Dokument (Min.)",
    rate: "Ihr Stundensatz (€)",
    unpaid: "Offene Rechnungen pro Monat (€)",
    hoursSaved: "Gewonnene Stunden / Monat",
    moneySaved: "Wert der gewonnenen Zeit",
    recovered: "Schneller eingenommene Liquidität",
    roi: "Rendite",
    perMonth: "/ Monat",
    note: "Annahmen: 3 Min. pro Dokument mit Biltov, 30 % der offenen Rechnungen dank der Mahnungen früher bezahlt. Eine Schätzung, kein Versprechen.",
    cta: "Diese Zeit zurückgewinnen",
  },
  pricing: {
    eyebrow: "Preise",
    title: "Drei Tarife, überall unbegrenzte Angebote.",
    subtitle: "Der Preis richtet sich nach der Größe Ihres Unternehmens, nicht nach der Zahl der Angebote. Preise ohne MwSt., ohne Bindung.",
    monthly: "Monatlich",
    yearly: "Jährlich",
    save: "2 Monate geschenkt",
    perMonth: "€ netto / Monat",
    billedYearly: "also {p} € netto, einmal jährlich berechnet",
    billedMonthly: "Ohne Bindung, jederzeit kündbar",
    vatNote: "Zuzüglich 21 % belgischer MwSt.",
    popular: "Am beliebtesten",
    cta: "5 Tage kostenlos testen",
    guarantee: "5 Tage mit allen Funktionen von Max · Ohne Bankkarte · Danach wählen Sie Ihren Tarif",
    unlimitedQuotes: "Unbegrenzte Angebote",
    invoices: "{n} Peppol-Rechnungen gesendet / Monat",
    overage: "danach {p} € netto pro weiterer Rechnung",
    users1: "1 Benutzer",
    usersN: "Bis zu {n} Benutzer",
    usersInf: "Unbegrenzte Benutzer",
    plans: {
      starter: {
        audience: "Einzelhandwerker",
        points: [
          "Angebote, Rechnungen und PDF-Export",
          "Belgische MwSt., Peppol, Mahnungen",
          "Kunden, Baustellen, Katalog, Bank",
        ],
      },
      pro: {
        audience: "Kleines Team",
        points: [
          "Alles aus Starter",
          "Lager, Einkauf, Fuhrpark, Werkzeuge",
          "Kalender, Verträge, Zusatzmodule",
        ],
      },
      max: {
        audience: "Strukturierter Betrieb",
        points: [
          "Alles aus Pro",
          "Mitarbeiter, Zeiterfassung, Arbeiterbereich",
          "Individuelle Rollen, Nachunternehmer pro Zeile",
          "Gantt, Schlechtwetter, Materialanalyse, 3D-Modus",
        ],
      },
    },
    compareTitle: "Tarife vergleichen",
    compareLink: "Tarife im Detail vergleichen",
    rows: {
      price: "Preis netto / Monat",
      invoices: "Peppol-Rechnungen gesendet / Monat",
      overage: "Über dem Kontingent",
      overageBlocked: "Wechsel zu höherem Tarif",
      users: "Benutzer",
      quotes: "Angebote",
      unlimited: "Unbegrenzt",
      docs: "Angebote, Rechnungen und PDF-Export",
      crm: "Kunden, Baustellen und Katalog",
      money: "Offene Forderungen, Bank und Buchhaltungsexporte",
      stock: "Lager",
      ops: "Einkauf, Fuhrpark, Werkzeuge und Verträge",
      planning: "Kalender und Zusatzmodule",
      team: "Mitarbeiter, Zeiterfassung und Arbeiterbereich",
      roles: "Individuelle Rollen (Super-Admin)",
      subcontract: "Nachunternehmer pro Zeile",
      gantt: "Gantt und Schlechtwetterkalender",
      profit: "Rentabilität und Materialanalyse",
      mode3d: "3D-Modus",
    },
    faqTitle: "Fragen zu den Tarifen",
    faq: [
      {
        q: "Sind Angebote wirklich unbegrenzt?",
        a: "Ja, in allen Tarifen. Gezählt werden nur über Peppol gesendete Rechnungen: Das ist der einzige Versand, der uns etwas kostet.",
      },
      {
        q: "Was passiert, wenn ich mein Kontingent erreiche?",
        a: "Bei 80 % und 100 % erscheint ein Hinweis. In Starter und Pro wird der Peppol-Versand bis zum nächsten Zeitraum gesperrt, oder Sie wechseln mit einem Klick zum höheren Tarif. In Max wird jede weitere Rechnung am Ende des Zeitraums berechnet.",
      },
      {
        q: "Kann ich den Tarif wechseln?",
        a: "Jederzeit, anteilig. Bei einem Wechsel nach unten zeigt Biltov zuerst, was den neuen Tarif überschreitet (Benutzer, Module). Es werden nie Daten gelöscht.",
      },
      {
        q: "Und nach dem Test?",
        a: "Ihre Daten bleiben schreibgeschützt einsehbar, bis Sie einen Tarif wählen. Nichts wird gelöscht.",
      },
      {
        q: "Wie wird bezahlt?",
        a: "Per Karte, Bancontact oder Lastschrift über Stripe. Die belgische MwSt. von 21 % wird hinzugefügt, und Sie erhalten jeden Monat (oder jedes Jahr) eine Rechnung.",
      },
    ],
  },
  faq: {
    eyebrow: "FAQ",
    title: "Häufige Fragen",
    items: [
      { q: "Funktioniert das Diktat auf einer lauten Baustelle?", a: "Die Spracherkennung ist die Ihres Browsers (Chrome, Edge, Safari). Sprechen Sie bei Lärm nah am Telefon. Sie können den Satz auch tippen und jede Zeile vor dem Senden korrigieren." },
      { q: "Entsprechen meine Angebote und Rechnungen den belgischen Regeln?", a: "Biltov wendet die Pflichtangaben, eine fortlaufende Nummerierung, den Satz von 6, 12 oder 21 % je nach Art der Arbeiten und Alter der Wohnung, die Umkehrung der Steuerschuld für steuerpflichtige Kunden und die strukturierte Mitteilung an. Die verwendeten Sätze und Schwellen sind in den Einstellungen datiert und mit Quelle hinterlegt: Lassen Sie sie von Ihrem Buchhalter prüfen." },
      { q: "Und Peppol, Pflicht zwischen Unternehmen?", a: "Biltov erstellt die Rechnung im Format Peppol BIS 3.0 (UBL). Derzeit reichen Sie diese Datei bei Ihrem Peppol-Dienstleister ein; der direkte Versand aus Biltov kommt mit dem Server." },
      { q: "Ist für den Test eine Bankkarte nötig?", a: "Nein. Legen Sie einfach Ihr Konto an (E-Mail und Passwort) und nutzen Sie Biltov 5 Tage kostenlos, ohne Karte. Danach wählen Sie den Tarif Starter, Pro oder Max (siehe Preise); ohne Tarif bleiben Ihre Daten schreibgeschützt einsehbar." },
      { q: "Müssen meine Kunden etwas installieren?", a: "Nein. Sie erhalten das PDF per E-Mail, WhatsApp oder SMS. Unterschrieben wird auf Ihrem Telefon oder Tablet, direkt auf der Baustelle." },
      { q: "Kann ich meine Kunden und meinen Katalog importieren?", a: "Ja, per Excel- oder CSV-Datei: Sie ordnen die Spalten zu, Biltov simuliert den Import und meldet Fehler vor dem Speichern. Die Preisdatei Ihres Händlers können Sie erneut importieren, um Ihre Preise zu aktualisieren." },
      { q: "Wo werden meine Daten gespeichert?", a: "Derzeit auf Ihrem Gerät (im Browser), mit verschlüsseltem Passwort. Exportieren Sie regelmäßig eine vollständige Sicherung in den Einstellungen. Die Synchronisierung zwischen Geräten kommt mit dem Server." },
      { q: "Und wenn ich aufhören möchte?", a: "Sie kündigen jederzeit. Sie können Ihre Daten exportieren: vollständige Sicherung und Buchhaltungsjournale als CSV oder Excel." },
    ],
  },
  footer: {
    tagline: "Der Sprach- und Rechnungsassistent für Bauhandwerker in Belgien.",
    product: "Produkt",
    company: "Unternehmen",
    legal: "Rechtliches",
    links: {
      product: ["Funktionen", "Gewerke", "Preis", "Rechner", "Demo"],
      company: ["Über uns", "Kontakt"],
      legal: ["Impressum", "Allgemeine Geschäftsbedingungen", "Datenschutzerklärung", "Cookies"],
    },
    compliance: ["Belgische MwSt.", "Peppol BIS 3.0", "DE · FR · NL"],
    rights: "Alle Rechte vorbehalten.",
    made: "Gemacht für Bauhandwerker in Belgien.",
  },
};
