import type { Dict } from "./fr";

export const de: Dict = {
  meta: {
    title: "Biltov — Der KI-Sprach- und Rechnungsassistent für Handwerker am Bau",
    description:
      "Diktieren Sie Angebote direkt auf der Baustelle. Biltov kalkuliert, gestaltet, versendet per E-Mail und WhatsApp und mahnt offene Rechnungen automatisch.",
  },
  nav: {
    features: "Funktionen",
    trades: "Gewerke",
    pricing: "Preis",
    roi: "ROI-Rechner",
    cta: "1 Tag kostenlos testen",
    dashboard: "Mein Konto",
    language: "Sprache",
    openMenu: "Menü öffnen",
    closeMenu: "Menü schließen",
  },
  hero: {
    badge: "Neu · KI-Sprachdiktat in 3 Sprachen",
    titleA: "Stift weg.",
    titleHighlight: "Einfach sprechen.",
    titleB: "Biltov erledigt den Papierkram.",
    subtitle:
      "Das Angebot ist in 30 Sekunden auf der Baustelle diktiert. Biltov kalkuliert es, gestaltet es in Ihren Farben, verschickt es per E-Mail und WhatsApp — und erinnert Ihre Kunden bis zur Zahlung.",
    ctaPrimary: "Sprachdiktat testen",
    ctaSecondary: "Konto erstellen",
    reassurance: ["EU-USt-konform", "1 Tag kostenlos testen", "Daten in der EU gehostet"],
    stats: [
      { value: "30 s", label: "für ein komplettes Angebot" },
      { value: "6 Std.", label: "pro Woche gespart" },
      { value: "-72 %", label: "Zahlungsverzug" },
    ],
    canvasHint: "Bewegen Sie die Maus, um die Baustelle zu drehen",
    scroll: "Scrollen",
  },
  trades: {
    eyebrow: "Gewerke-Onboarding",
    title: "Biltov spricht Ihr Gewerk.",
    subtitle: "Wählen Sie Ihr Gewerk: Oberfläche, Fachbegriffe und Materialkatalog passen sich sofort an.",
    labels: {
      dictation: "Sie diktieren",
      generated: "Biltov erstellt",
      supplies: "Materialkatalog",
      jargon: "Verstandene Fachbegriffe",
      vat: "Angewandte USt.",
      total: "Summe netto",
      designation: "Position",
      qty: "Menge",
      price: "EP netto",
    },
    list: [
      {
        id: "plombier",
        name: "Installateur",
        voice: "Austausch 200-Liter-Warmwasserspeicher bei Frau Laurent, mit Sicherheitsgruppe, PEX-Verbindern und 3 Stunden Arbeitszeit.",
        lines: [
          { label: "Elektro-Warmwasserspeicher 200 L, stehend", qty: 1, unit: "Stk", price: 489 },
          { label: "Sicherheitsgruppe + Siphon", qty: 1, unit: "Stk", price: 42 },
          { label: "PEX-Verbinder Ø16 + Schellen", qty: 1, unit: "Pausch.", price: 36 },
          { label: "Arbeitszeit Installateur", qty: 3, unit: "Std", price: 55 },
        ],
        supplies: ["PEX Ø16 / Ø20", "Verbundrohr", "Messingfittings", "Mischbatterien", "Siphons", "Kugelhähne"],
        jargon: ["Sicherheitsgruppe", "PEX", "Verbundrohr", "Rückflussverhinderer", "Strangregulierventil"],
        vat: "10 % (Renovierung, FR)",
      },
      {
        id: "electricien",
        name: "Elektriker",
        voice: "Erneuerung Verteiler für Herrn Girard, 3-reihig, zwei FI-Schalter 30 mA, 12 Leitungsschutzschalter und 6 Steckdosen.",
        lines: [
          { label: "Unterverteiler 3-reihig, 39 TE", qty: 1, unit: "Stk", price: 128 },
          { label: "FI-Schalter 40 A 30 mA Typ A", qty: 2, unit: "Stk", price: 74 },
          { label: "Leitungsschutzschalter B16", qty: 12, unit: "Stk", price: 11.5 },
          { label: "Unterputz-Steckdose inkl. Montage", qty: 6, unit: "Stk", price: 38 },
        ],
        supplies: ["LS-Schalter", "FI 30 mA", "Leerrohr", "NYM-Kabel", "Unterputzdosen", "Phasenschienen"],
        jargon: ["FI Typ A", "VDE 0100", "Phasenschiene", "Leerrohr", "Schuko"],
        vat: "10 % (Renovierung, FR)",
      },
      {
        id: "peintre",
        name: "Maler",
        voice: "Schlafzimmer 14 m² bei Familie Moreau: abwaschen, spachteln, grundieren und zwei Anstriche seidenmatt weiß auf 38 m² Wand, Decke matt.",
        lines: [
          { label: "Wände abwaschen + spachteln + schleifen", qty: 38, unit: "m²", price: 6 },
          { label: "Tiefgrund Acryl", qty: 38, unit: "m²", price: 4.5 },
          { label: "Seidenmatt weiß, 2 Anstriche", qty: 38, unit: "m²", price: 14 },
          { label: "Decke matt, 2 Anstriche", qty: 14, unit: "m²", price: 17 },
        ],
        supplies: ["Lack / Dispersion", "Spachtelmasse", "Fugenband", "Rollen 180 mm", "Abdeckfolie", "Malerkrepp"],
        jargon: ["seidenmatt", "Grundierung", "Q3-Spachtelung", "Zwischenschliff", "stumpfmatt"],
        vat: "10 % (Instandhaltung, FR)",
      },
      {
        id: "macon",
        name: "Maurer",
        voice: "Betonplatte 25 m² für die Terrasse von Herrn Petit, 12 Zentimeter, Baustahlmatte, 20 cm Schotter und Randschalung.",
        lines: [
          { label: "Aushub + Schottertragschicht 20 cm", qty: 25, unit: "m²", price: 28 },
          { label: "Baustahlmatte Q188", qty: 25, unit: "m²", price: 7.5 },
          { label: "Beton C25/30, 12 cm, eingebaut", qty: 3, unit: "m³", price: 165 },
          { label: "Randschalung", qty: 20, unit: "lfm", price: 18 },
        ],
        supplies: ["Beton C25/30", "Hohlblocksteine", "Baustahlmatten", "Bewehrungsstahl", "Mörtel", "PE-Folie"],
        jargon: ["Schottertragschicht", "Ringanker", "Bewehrung", "Estrich", "Sturz"],
        vat: "20 % (Neubau, FR)",
      },
      {
        id: "menuisier",
        name: "Tischler",
        voice: "Einbau von 3 Kunststofffenstern mit Doppelverglasung 120 mal 135 bei Frau Roux, Ausbau der alten Holzfenster, plus Verkleidung und Dichtungen.",
        lines: [
          { label: "Kunststofffenster 2-flügelig 120×135 Uw 1,3", qty: 3, unit: "Stk", price: 540 },
          { label: "Ausbau Bestandsfenster Holz", qty: 3, unit: "Stk", price: 65 },
          { label: "Verkleidung + Abdeckleisten", qty: 3, unit: "Stk", price: 48 },
          { label: "Dichtstoff + PU-Schaum + Kompriband", qty: 1, unit: "Pausch.", price: 45 },
        ],
        supplies: ["Fenster PVC / Alu", "Kompriband", "PU-Schaum", "Abdeckleisten", "Schnellbauschrauben", "Beschläge"],
        jargon: ["Blendrahmen", "Flügel", "Renovierungsrahmen", "Uw-Wert", "Kompriband"],
        vat: "5,5 % (energetische Sanierung, FR)",
      },
    ],
  },
  features: {
    eyebrow: "Funktionen",
    title: "Ihr ganzes Büro in der Hosentasche.",
    subtitle: "Fünf Module, gemacht für die Baustelle, nicht fürs Büro. Ein Abo, alles inklusive.",
    voice: {
      title: "Sprachdiktat & KI-Text",
      desc: "Sprechen Sie wie auf der Baustelle. Die KI strukturiert, kalkuliert und gestaltet ein unterschriftsreifes PDF-Angebot.",
      listening: "Hört zu…",
      thinking: "KI kalkuliert…",
      ready: "PDF fertig",
      transcript: "„Bad bei Durand, Wandfliesen 18 m², bodengleiche Duschwanne einbauen, 2 Tage Arbeitszeit“",
      pdfLines: ["Wandfliesen 30×60 — 18 m²", "Flache Duschwanne 90×120", "Arbeitszeit Fliesenleger — 2 Tage"],
      quote: "ANGEBOT Nr. 2026-142",
    },
    channels: {
      title: "Mehrkanal-Versand",
      desc: "Ein Klick: Das Angebot geht gleichzeitig per E-Mail, WhatsApp und SMS raus.",
      email: "E-Mail",
      whatsapp: "WhatsApp",
      sms: "SMS",
      send: "Angebot senden",
      sending: "Wird gesendet…",
      delivered: "Zugestellt",
      reset: "Neu starten",
      none: "Mindestens einen Kanal aktivieren",
    },
    reminders: {
      title: "Automatische Zahlungserinnerungen",
      desc: "Biltov mahnt für Sie — im richtigen Ton, zur richtigen Zeit. Sie bleiben der Nette.",
      steps: [
        { day: "T+7", title: "Freundliche Erinnerung", msg: "Guten Tag Herr Durand, kurze Erinnerung: Rechnung F-2026-088 (1.240 €) ist fällig. Zahlungslink anbei 🙂" },
        { day: "T+14", title: "Deutliche Mahnung", msg: "Guten Tag Herr Durand, Rechnung F-2026-088 ist leider noch offen. Bitte begleichen Sie sie innerhalb von 7 Tagen." },
        { day: "T+21", title: "Letzte Mahnung", msg: "Letzte Aufforderung zur Zahlung der Rechnung F-2026-088 binnen 8 Tagen; Verzugszinsen und 40 € Pauschale fallen an." },
      ],
      paid: "Bezahlt an T+9 — Erinnerungen gestoppt",
      markPaid: "Zahlung simulieren",
    },
    photo: {
      title: "Fotos & Marge",
      desc: "Vorher/Nachher-Fotos mit Zeitstempel in der Baustellenakte. Belege scannen: Die Marge rechnet sich selbst.",
      before: "Vorher",
      after: "Nachher",
      scan: "Beleg scannen",
      scanning: "KI liest…",
      receipt: "Beleg Baustoffhandel",
      items: [
        { label: "Fliesenkleber C2 × 4", value: 86.4 },
        { label: "Fugenkreuze 3 mm", value: 7.9 },
        { label: "Fugenmörtel grau 5 kg", value: 18.5 },
      ],
      billed: "An Kunden berechnet",
      costs: "Einkauf",
      margin: "Baustellenmarge",
    },
    brand: {
      title: "Branding & Export",
      desc: "Ihr Logo, Ihre Farben, Ihre IBAN. Mehrländer-USt. automatisch berechnet.",
      upload: "Logo hochladen",
      color: "Farbe",
      country: "Land / USt.",
      iban: "IBAN",
      company: "Dupont Renovierung",
      preview: "PDF-Vorschau",
      subtotal: "Netto",
      vat: "USt.",
      total: "Brutto",
    },
  },
  demo: {
    eyebrow: "Live-Demo",
    title: "Sagen Sie es. Das Angebot füllt sich.",
    subtitle: "Wählen Sie einen Beispielsatz, tippen Sie Ihren eigenen oder nutzen Sie Ihr Mikrofon: Das Angebot entsteht Zeile für Zeile, in Echtzeit.",
    examples: [
      "Für Frau Martin, 24 m² Eichenparkett verlegen zu 45 Euro, 12 lfm Sockelleisten zu 9 Euro und 6 Stunden Arbeitszeit zu 50 Euro",
      "Für Herrn Bernard, 3 Steckdosen zu 38 Euro, ein 2-reihiger Verteiler zu 180 Euro und 4 Stunden Arbeitszeit zu 55 Euro",
      "Für die Horizon GmbH, 60 m² Wände streichen zu 22 Euro und 18 m² Decke zu 25 Euro",
    ],
    placeholder: "Z. B.: Für Herrn Dubois, 10 m² Fliesen zu 40 Euro und 5 Stunden zu 50 Euro",
    simulate: "Diktat starten",
    mic: "Mikrofon nutzen",
    stop: "Stopp",
    micUnsupported: "Mikrofon in diesem Browser nicht verfügbar — nutzen Sie ein Beispiel.",
    listening: "Biltov hört zu…",
    reset: "Löschen",
    live: "Live-Transkript",
    pdf: {
      quote: "ANGEBOT",
      number: "Nr. 2026-",
      client: "Kunde",
      clientUnknown: "Kunde noch offen",
      date: "Datum",
      designation: "Position",
      qty: "Menge",
      unitPrice: "EP",
      total: "Gesamt",
      subtotal: "Netto",
      vat: "USt. 20 %",
      totalTTC: "Brutto",
      validity: "Angebot 30 Tage gültig · Auftrag erteilt:",
      empty: "Die Positionen erscheinen hier während des Diktats…",
      labour: "Arbeitszeit",
    },
  },
  roi: {
    eyebrow: "ROI-Rechner",
    title: "Was bringt Ihnen Biltov?",
    subtitle: "Passen Sie die Regler an Ihren Betrieb an. Die Rechnung ist bewusst vorsichtig.",
    quotes: "Angebote & Rechnungen pro Monat",
    minutes: "Aktuelle Zeit pro Dokument (Min.)",
    rate: "Ihr Stundensatz (€)",
    unpaid: "Offene Forderungen pro Monat (€)",
    hoursSaved: "Gewonnene Stunden / Monat",
    moneySaved: "Wert der gesparten Zeit",
    recovered: "Schneller eingenommene Liquidität",
    roi: "Return on Investment",
    perMonth: "/ Monat",
    note: "Annahmen: 3 Min. pro Dokument mit Biltov, 30 % der offenen Forderungen dank Erinnerungen früher bezahlt.",
    cta: "Diese Zeit zurückholen",
  },
  pricing: {
    eyebrow: "Ein Preis",
    title: "Ein Preis. Alles drin. Punkt.",
    subtitle: "Keine Stufen, keine versteckten Optionen, kein Angebotslimit. Alle Funktionen für alle.",
    monthly: "Monatlich",
    yearly: "Jährlich",
    save: "-20 %",
    badge: "Alles inklusive · Ohne Bindung",
    plan: "Biltov Pro",
    perMonth: "€ netto / Monat",
    billedYearly: "also 768 € netto, einmal jährlich abgerechnet",
    billedMonthly: "Mit 1 Klick jederzeit kündbar",
    features: [
      "Unbegrenztes KI-Sprachdiktat (FR / EN / DE)",
      "Unbegrenzt rechtskonforme Angebote & Rechnungen",
      "Versand per E-Mail + WhatsApp + SMS",
      "Automatische Erinnerungen T+7 / T+14 / T+21",
      "KI-Belegscan & Margenkontrolle",
      "Vorher/Nachher-Baustellenfotos",
      "Mehrländer-USt. & ZUGFeRD / Factur-X",
      "Ihr Logo, Ihre Farben, Ihre IBAN",
      "Priorisierter persönlicher Support, 6 Tage/Woche",
    ],
    cta: "1 Tag kostenlos starten",
    guarantee: "1 Tag gratis · Karte erforderlich · Danach automatische Abbuchung · Jederzeit kündbar",
    roiLine: "Rechnet sich schon ab 1,5 Stunden gesparter Büroarbeit pro Monat.",
  },
  faq: {
    eyebrow: "FAQ",
    title: "Häufige Fragen",
    items: [
      { q: "Funktioniert das Diktat auf einer lauten Baustelle?", a: "Ja. Das Modell ist auf laute Umgebungen (Bohrer, Mischer, Verkehr) trainiert und kennt das Bau-Vokabular. Vor dem Versand können Sie jede Zeile per Finger korrigieren." },
      { q: "Sind meine Angebote und Rechnungen rechtskonform?", a: "Ja: Pflichtangaben, fortlaufende Nummerierung, USt. je Steuersatz (europäische Sätze), Reverse-Charge für Subunternehmer und ZUGFeRD/Factur-X für die E-Rechnung." },
      { q: "Brauche ich eine Kreditkarte für den Test?", a: "Ja. Sie hinterlegen Ihre Karte beim Start und nutzen Biltov 1 Tag lang kostenlos. Ohne Kündigung vor Testende wird das Abo danach automatisch monatlich (oder jährlich) abgebucht. Kündigung mit einem Klick, kostenlos." },
      { q: "Müssen meine Kunden etwas installieren?", a: "Nein. Sie erhalten einen sicheren Link per E-Mail, WhatsApp oder SMS zum Ansehen, digitalen Unterschreiben und Bezahlen." },
      { q: "Kann ich Kunden und Katalog importieren?", a: "Ja, per CSV-/Excel-Import oder aus Ihrer bisherigen Software. Unser Team übernimmt das während des Tests auf Wunsch kostenlos." },
      { q: "Wo werden meine Daten gespeichert?", a: "In Rechenzentren in der Europäischen Union, verschlüsselt im Ruhezustand und bei der Übertragung. Biltov ist DSGVO-konform und Sie bleiben Eigentümer Ihrer Daten." },
      { q: "Und wenn ich aufhören möchte?", a: "Sie kündigen mit einem Klick in Ihrem Konto, kostenlos. Alle Angebote, Rechnungen und Kunden lassen sich jederzeit exportieren." },
    ],
  },
  footer: {
    tagline: "Der KI-Sprach- und Rechnungsassistent für Handwerker am Bau.",
    product: "Produkt",
    company: "Unternehmen",
    legal: "Rechtliches",
    links: {
      product: ["Funktionen", "Gewerke", "Preis", "ROI-Rechner", "Demo"],
      company: ["Über uns", "Baustellen-Blog", "Handelspartner", "Kontakt"],
      legal: ["Impressum", "AGB / Nutzungsbedingungen", "Datenschutz", "Cookie-Einstellungen", "AVV (DSGVO)"],
    },
    compliance: ["DSGVO-konform", "EU-USt. & ZUGFeRD", "In der EU gehostet"],
    rights: "Alle Rechte vorbehalten.",
    made: "Gemacht für Bauprofis, in Europa.",
    newsletter: "1 Baustellen-Tipp pro Monat",
    email: "ihre@email.de",
    subscribe: "Abonnieren",
    subscribed: "Danke, eingetragen!",
  },
};
