import type { Dict } from "./fr";

export const en: Dict = {
  meta: {
    title: "Biltov — The AI voice & invoicing assistant for construction trades",
    description:
      "Dictate your quotes on site. Biltov prices them, lays them out, sends them by email and WhatsApp, and chases unpaid invoices automatically.",
  },
  nav: {
    features: "Features",
    trades: "Trades",
    pricing: "Pricing",
    roi: "ROI Calculator",
    cta: "14-Day Free Trial",
    language: "Language",
    openMenu: "Open menu",
    closeMenu: "Close menu",
  },
  hero: {
    badge: "New · AI voice dictation in 3 languages",
    titleA: "Put the pen down.",
    titleHighlight: "Just talk.",
    titleB: "Biltov handles the paperwork.",
    subtitle:
      "Dictate a quote in 30 seconds from the job site. Biltov prices it, brands it with your colours, sends it by email and WhatsApp — then chases your clients until they pay.",
    ctaPrimary: "Try Voice Dictation",
    ctaSecondary: "See pricing",
    reassurance: ["EU VAT compliant", "No credit card required", "Data hosted in the EU"],
    stats: [
      { value: "30 s", label: "for a complete quote" },
      { value: "6 h", label: "saved every week" },
      { value: "-72%", label: "late payments" },
    ],
    canvasHint: "Move your mouse to orbit the site",
    scroll: "Scroll",
  },
  trades: {
    eyebrow: "Trade onboarding",
    title: "Biltov speaks your trade.",
    subtitle: "Pick your trade: the interface, vocabulary and supplies catalogue adapt instantly.",
    labels: {
      dictation: "You say",
      generated: "Biltov generates",
      supplies: "Supplies catalogue",
      jargon: "Jargon understood",
      vat: "VAT applied",
      total: "Total excl. VAT",
      designation: "Item",
      qty: "Qty",
      price: "Unit price",
    },
    list: [
      {
        id: "plombier",
        name: "Plumber",
        voice: "Replace a 200-litre water heater at Mrs Laurent's, with safety valve group, PEX fittings and 3 hours of labour.",
        lines: [
          { label: "Electric water heater 200 L, vertical", qty: 1, unit: "pc", price: 489 },
          { label: "Safety valve group + trap", qty: 1, unit: "pc", price: 42 },
          { label: "PEX fittings Ø16 + clamps", qty: 1, unit: "set", price: 36 },
          { label: "Plumber labour", qty: 3, unit: "h", price: 55 },
        ],
        supplies: ["PEX Ø16 / Ø20", "Multilayer pipe", "Brass fittings", "Mixer taps", "Traps", "Quarter-turn valves"],
        jargon: ["safety group", "PEX", "multilayer", "check valve", "balancing tee"],
        vat: "10% (renovation > 2 yrs, FR)",
      },
      {
        id: "electricien",
        name: "Electrician",
        voice: "Consumer unit upgrade for Mr Girard, 3-row board, two 30 mA RCDs, 12 breakers and 6 sockets.",
        lines: [
          { label: "Consumer unit, 3 rows, 39 modules", qty: 1, unit: "pc", price: 128 },
          { label: "RCD 40 A 30 mA type A", qty: 2, unit: "pc", price: 74 },
          { label: "Circuit breaker 16 A", qty: 12, unit: "pc", price: 11.5 },
          { label: "Flush socket + installation", qty: 6, unit: "pc", price: 38 },
        ],
        supplies: ["Breakers", "30 mA RCDs", "Conduit", "Cable", "Back boxes", "Busbars"],
        jargon: ["type A RCD", "wiring regs", "busbar", "conduit", "double socket"],
        vat: "10% (renovation, FR)",
      },
      {
        id: "peintre",
        name: "Painter",
        voice: "14 m² bedroom at the Moreaus': wash down, fill, primer and two coats of white eggshell on 38 m² of walls, matt ceiling.",
        lines: [
          { label: "Wash down + fill + sand walls", qty: 38, unit: "m²", price: 6 },
          { label: "Acrylic primer", qty: 38, unit: "m²", price: 4.5 },
          { label: "White eggshell, 2 coats", qty: 38, unit: "m²", price: 14 },
          { label: "Ceiling matt paint, 2 coats", qty: 14, unit: "m²", price: 17 },
        ],
        supplies: ["Oil / Acrylic paint", "Skim filler", "Joint tape", "180 mm rollers", "Dust sheets", "Masking tape"],
        jargon: ["eggshell", "primer", "skim coat", "de-nib", "dead flat"],
        vat: "10% (maintenance work, FR)",
      },
      {
        id: "macon",
        name: "Mason",
        voice: "25 m² concrete slab for Mr Petit's terrace, 12 centimetres, welded mesh, 20 cm hardcore and perimeter formwork.",
        lines: [
          { label: "Excavation + 20 cm hardcore", qty: 25, unit: "m²", price: 28 },
          { label: "Welded mesh ST25C", qty: 25, unit: "m²", price: 7.5 },
          { label: "C25/30 concrete, 12 cm, poured", qty: 3, unit: "m³", price: 165 },
          { label: "Perimeter formwork", qty: 20, unit: "lm", price: 18 },
        ],
        supplies: ["C25/30 concrete", "Blocks 20", "ST25 mesh", "Rebar", "Mortar", "DPM sheet"],
        jargon: ["hardcore", "ring beam", "rebar", "screed", "lintel"],
        vat: "20% (new build, FR)",
      },
      {
        id: "menuisier",
        name: "Carpenter",
        voice: "Fit 3 double-glazed PVC windows 120 by 135 at Mrs Roux's, remove the old wooden ones, plus trims and seals.",
        lines: [
          { label: "PVC casement window 120×135 Uw 1.3", qty: 3, unit: "pc", price: 540 },
          { label: "Removal of existing timber window", qty: 3, unit: "pc", price: 65 },
          { label: "PVC trims + cover strips", qty: 3, unit: "pc", price: 48 },
          { label: "Sealant + PU foam + expanding tape", qty: 1, unit: "set", price: 45 },
        ],
        supplies: ["PVC / Alu windows", "Expanding tape", "PU foam", "Cover strips", "Drywall screws", "Hardware"],
        jargon: ["frame", "sash", "retrofit on frame", "Uw", "expanding tape"],
        vat: "5.5% (energy renovation, FR)",
      },
    ],
  },
  features: {
    eyebrow: "Features",
    title: "Your whole office, in your pocket.",
    subtitle: "Five modules built for the job site, not the office. One subscription, everything included.",
    voice: {
      title: "Voice dictation & AI text",
      desc: "Talk like you do on site. The AI structures, prices and lays out a PDF quote ready to sign.",
      listening: "Listening…",
      thinking: "AI is pricing…",
      ready: "PDF ready",
      transcript: "“Bathroom at Durand's, 18 m² wall tiles, fit a low-profile shower tray, 2 days of labour”",
      pdfLines: ["Wall tiles 30×60 — 18 m²", "Low-profile shower tray 90×120", "Tiler labour — 2 days"],
      quote: "QUOTE No. 2026-142",
    },
    channels: {
      title: "Multi-channel delivery",
      desc: "One click: the quote goes out by email, WhatsApp and SMS at once.",
      email: "Email",
      whatsapp: "WhatsApp",
      sms: "SMS",
      send: "Send quote",
      sending: "Sending…",
      delivered: "Delivered",
      reset: "Start over",
      none: "Enable at least one channel",
    },
    reminders: {
      title: "Automatic payment reminders",
      desc: "Biltov chases for you, with the right tone at the right time. You stay the nice guy.",
      steps: [
        { day: "D+7", title: "Friendly reminder", msg: "Hi Mr Durand, quick reminder: invoice F-2026-088 (€1,240) is now due. Payment link attached 🙂" },
        { day: "D+14", title: "Firm reminder", msg: "Hi Mr Durand, unless we're mistaken invoice F-2026-088 is still unpaid. Please settle within 7 days." },
        { day: "D+21", title: "Formal notice", msg: "Formal notice to pay invoice F-2026-088 within 8 days; late-payment interest and a €40 fixed fee will apply." },
      ],
      paid: "Paid on D+9 — reminders stopped",
      markPaid: "Simulate a payment",
    },
    photo: {
      title: "Photos & margin tracking",
      desc: "Time-stamped before/after photos in the job file. Scan your receipts: your margin calculates itself.",
      before: "Before",
      after: "After",
      scan: "Scan a receipt",
      scanning: "AI reading…",
      receipt: "Builder's merchant receipt",
      items: [
        { label: "C2 tile adhesive × 4", value: 86.4 },
        { label: "Tile spacers 3 mm", value: 7.9 },
        { label: "Grey grout 5 kg", value: 18.5 },
      ],
      billed: "Billed to client",
      costs: "Purchases",
      margin: "Job margin",
    },
    brand: {
      title: "Branding & export",
      desc: "Your logo, your colours, your IBAN. Multi-country VAT calculated automatically.",
      upload: "Upload your logo",
      color: "Colour",
      country: "Country / VAT",
      iban: "IBAN",
      company: "Dupont Renovation",
      preview: "PDF preview",
      subtotal: "Subtotal",
      vat: "VAT",
      total: "Total incl. VAT",
    },
  },
  demo: {
    eyebrow: "Live demo",
    title: "Say it. Watch the quote fill itself.",
    subtitle: "Pick an example sentence, type your own or use your microphone: the quote builds line by line, in real time.",
    examples: [
      "For Mrs Martin, 24 m² of oak flooring at 45 euros, 12 lm of skirting at 9 euros and 6 hours of labour at 50 euros",
      "For Mr Bernard, 3 electrical sockets at 38 euros, a 2-row consumer unit at 180 euros and 4 hours of labour at 55 euros",
      "For Horizon Ltd, painting 60 m² of walls at 22 euros and 18 m² of ceiling at 25 euros",
    ],
    placeholder: "E.g.: For Mr Dubois, 10 m² of tiling at 40 euros and 5 hours at 50 euros",
    simulate: "Start dictation",
    mic: "Use microphone",
    stop: "Stop",
    micUnsupported: "Microphone not available in this browser — use an example.",
    listening: "Biltov is listening…",
    reset: "Clear",
    live: "Live transcript",
    pdf: {
      quote: "QUOTE",
      number: "No. 2026-",
      client: "Client",
      clientUnknown: "Client to be confirmed",
      date: "Date",
      designation: "Item",
      qty: "Qty",
      unitPrice: "Unit",
      total: "Total",
      subtotal: "Subtotal",
      vat: "VAT 20%",
      totalTTC: "Total incl. VAT",
      validity: "Quote valid for 30 days · Approved by:",
      empty: "Lines will appear here as you dictate…",
      labour: "Labour",
    },
  },
  roi: {
    eyebrow: "ROI calculator",
    title: "How much does Biltov earn you?",
    subtitle: "Adjust the sliders to your business. The maths is deliberately conservative.",
    quotes: "Quotes & invoices per month",
    minutes: "Current time per document (min)",
    rate: "Your hourly rate (€)",
    unpaid: "Outstanding unpaid per month (€)",
    hoursSaved: "Hours recovered / month",
    moneySaved: "Value of time saved",
    recovered: "Cash collected sooner",
    roi: "Return on investment",
    perMonth: "/ month",
    note: "Assumptions: 3 min per document with Biltov, 30% of unpaid invoices collected sooner thanks to reminders.",
    cta: "Win back this time",
  },
  pricing: {
    eyebrow: "One price",
    title: "One price. Everything included. Period.",
    subtitle: "No tiers, no hidden add-ons, no quote limits. Every feature for everyone.",
    monthly: "Monthly",
    yearly: "Yearly",
    save: "-20%",
    badge: "All inclusive · No commitment",
    plan: "Biltov Pro",
    perMonth: "€ excl. VAT / month",
    billedYearly: "i.e. €768 excl. VAT billed once a year",
    billedMonthly: "Cancel in 1 click, anytime",
    features: [
      "Unlimited AI voice dictation (FR / EN / DE)",
      "Unlimited compliant quotes & invoices",
      "Email + WhatsApp + SMS delivery",
      "Automatic reminders D+7 / D+14 / D+21",
      "AI receipt scanning & margin tracking",
      "Before / after site photos",
      "Multi-country VAT & Factur-X",
      "Your logo, your colours, your IBAN",
      "Priority human support, 6 days a week",
    ],
    cta: "Start your 14-day free trial",
    guarantee: "No card · No commitment · Export your data anytime",
    roiLine: "Pays for itself with just 1.5 hours of paperwork saved per month.",
  },
  faq: {
    eyebrow: "FAQ",
    title: "Frequently asked questions",
    items: [
      { q: "Does dictation work on a noisy job site?", a: "Yes. The model is trained on noisy environments (drills, mixers, traffic) and understands construction vocabulary. You can always fix a line with your finger before sending." },
      { q: "Are my quotes and invoices compliant?", a: "Yes: mandatory legal mentions, continuous numbering, VAT per rate (French and European rates), reverse charge for subcontracting, and Factur-X format ready for e-invoicing." },
      { q: "Do I need a credit card for the trial?", a: "No. The 14-day trial unlocks everything without a card. At the end you choose whether to continue — nothing is charged automatically." },
      { q: "Do my clients need to install anything?", a: "No. They receive a secure link by email, WhatsApp or SMS to view, e-sign and pay." },
      { q: "Can I import my clients and catalogue?", a: "Yes, via CSV / Excel import or from your previous software. Our team can do it for free during your trial." },
      { q: "Where is my data stored?", a: "In data centres located in the European Union, encrypted at rest and in transit. Biltov is GDPR compliant and you remain the owner of your data." },
      { q: "What if I want to stop?", a: "Cancel in one click from your account, free of charge. You can export all your quotes, invoices and clients at any time." },
    ],
  },
  footer: {
    tagline: "The AI voice & invoicing assistant for construction trades.",
    product: "Product",
    company: "Company",
    legal: "Legal",
    links: {
      product: ["Features", "Trades", "Pricing", "ROI Calculator", "Demo"],
      company: ["About", "Job-site blog", "Merchant partners", "Contact"],
      legal: ["Legal notice", "Terms of sale / use", "Privacy policy", "Cookie settings", "DPA (GDPR processing)"],
    },
    compliance: ["GDPR compliant", "EU VAT & Factur-X", "Hosted in the EU"],
    rights: "All rights reserved.",
    made: "Built for construction pros, in Europe.",
    newsletter: "Get 1 job-site tip a month",
    email: "you@email.com",
    subscribe: "Subscribe",
    subscribed: "Thanks, you're in!",
  },
};
