// Contenu de référence (FR). Les traductions EN / DE suivent exactement la même forme.

export type TradeId = "plombier" | "electricien" | "peintre" | "macon" | "menuisier" | "paysagiste";

export type QuoteLine = { label: string; qty: number; unit: string; price: number };

export type Trade = {
  id: TradeId;
  name: string;
  voice: string;
  lines: QuoteLine[];
  supplies: string[];
  jargon: string[];
  vat: string;
};

export const fr = {
  meta: {
    title: "Biltov — L'assistant vocal et de facturation des artisans du bâtiment en Belgique",
    description:
      "Dictez vos devis depuis le chantier en français, néerlandais ou allemand. Biltov applique la TVA belge, prépare vos factures Peppol et vous aide à encaisser.",
  },
  nav: {
    features: "Fonctionnalités",
    videos: "Vidéos",
    trades: "Métiers",
    pricing: "Tarif",
    about: "À propos",
    roi: "Calculateur",
    cta: "Essai gratuit 5 jours",
    dashboard: "Mon espace",
    language: "Langue",
    openMenu: "Ouvrir le menu",
    lightMode: "Mode jour",
    darkMode: "Mode nuit",
    closeMenu: "Fermer le menu",
  },
  hero: {
    badge: "Pour les artisans en Belgique · FR · NL · DE",
    titleA: "Posez le stylo.",
    titleHighlight: "Dictez.",
    titleB: "Biltov s'occupe de la paperasse.",
    subtitle:
      "Dictez le devis depuis le chantier : Biltov retrouve vos prix, applique le bon taux de TVA belge, le met en page à vos couleurs et vous aide à le faire signer, facturer et encaisser.",
    ctaPrimary: "Tester la dictée",
    ctaSecondary: "Voir la démo",
    reassurance: ["TVA belge 6 / 12 / 21 % et autoliquidation", "Factures Peppol BIS 3.0", "5 jours gratuits, sans carte"],
    stats: [
      { value: "30 s", label: "pour dicter un devis" },
      { value: "3", label: "langues : FR, NL, DE" },
      { value: "+++", label: "communication structurée sur chaque facture" },
    ],
    canvasHint: "Bougez la souris pour tourner autour du chantier",
    scroll: "Défiler",
  },
  trades: {
    eyebrow: "Votre métier",
    title: "Biltov parle votre métier.",
    subtitle: "Choisissez votre corps de métier : le vocabulaire et le catalogue de départ s'adaptent. Vos prix restent les vôtres.",
    labels: {
      dictation: "Vous dictez",
      generated: "Biltov prépare",
      supplies: "Catalogue de départ",
      jargon: "Vocabulaire compris",
      vat: "TVA appliquée",
      total: "Total HTVA",
      designation: "Désignation",
      qty: "Qté",
      price: "PU HTVA",
    },
    list: [
      {
        id: "plombier",
        name: "Plombier-chauffagiste",
        voice: "Pour Mme Laurent à Namur, remplacement du boiler électrique 200 litres, groupe de sécurité, raccords multicouche et 3 heures de main-d'œuvre.",
        lines: [
          { label: "Boiler électrique 200 L vertical", qty: 1, unit: "u", price: 489 },
          { label: "Groupe de sécurité + siphon", qty: 1, unit: "u", price: 42 },
          { label: "Raccords multicouche Ø16 + colliers", qty: 1, unit: "lot", price: 36 },
          { label: "Main-d'œuvre plombier", qty: 3, unit: "h", price: 55 },
        ],
        supplies: ["Multicouche Ø16 / Ø20", "Raccords laiton", "Boilers", "Mitigeurs", "Siphons", "Vannes 1/4 de tour"],
        jargon: ["boiler", "groupe de sécurité", "multicouche", "clapet anti-retour", "vase d'expansion"],
        vat: "6 % (logement privé de plus de 10 ans)",
      },
      {
        id: "electricien",
        name: "Électricien",
        voice: "Pour M. Janssens à Liège, remplacement du tableau, 2 différentiels 30 milliampères, 12 disjoncteurs, 6 prises et 5 heures de main-d'œuvre.",
        lines: [
          { label: "Coffret divisionnaire 3 rangées", qty: 1, unit: "u", price: 128 },
          { label: "Interrupteur différentiel 40 A 30 mA type A", qty: 2, unit: "u", price: 74 },
          { label: "Disjoncteur bipolaire 16 A", qty: 12, unit: "u", price: 11.5 },
          { label: "Prise encastrée + pose", qty: 6, unit: "u", price: 38 },
        ],
        supplies: ["Disjoncteurs", "Différentiels 30 mA", "Gaine", "Câble XVB / VOB", "Boîtes d'encastrement", "Peignes"],
        jargon: ["RGIE", "contrôle de conformité", "différentiel 30 mA", "tableau divisionnaire", "schéma unifilaire"],
        vat: "6 % (logement privé de plus de 10 ans)",
      },
      {
        id: "peintre",
        name: "Peintre",
        voice: "Pour la famille Dubois à Mons, lessivage, rebouchage, sous-couche et deux couches de latex blanc sur 38 m² de murs, plafond de 14 m² en mat.",
        lines: [
          { label: "Lessivage + rebouchage + ponçage murs", qty: 38, unit: "m²", price: 6 },
          { label: "Sous-couche acrylique", qty: 38, unit: "m²", price: 4.5 },
          { label: "Latex blanc 2 couches", qty: 38, unit: "m²", price: 14 },
          { label: "Plafond peinture mate 2 couches", qty: 14, unit: "m²", price: 17 },
        ],
        supplies: ["Latex / acrylique", "Enduit de lissage", "Bande à joint", "Rouleaux", "Bâches", "Papier de masquage"],
        jargon: ["latex", "fixatif", "enduisage", "égrenage", "mat profond"],
        vat: "6 % (logement privé de plus de 10 ans)",
      },
      {
        id: "macon",
        name: "Maçon",
        voice: "Pour M. Peeters à Wavre, dalle de terrasse de 25 m² dans une nouvelle construction, 12 centimètres, treillis, empierrement de 20 cm et coffrage.",
        lines: [
          { label: "Terrassement + empierrement 20 cm", qty: 25, unit: "m²", price: 28 },
          { label: "Treillis d'armature", qty: 25, unit: "m²", price: 7.5 },
          { label: "Béton C25/30 ép. 12 cm coulé", qty: 3, unit: "m³", price: 165 },
          { label: "Coffrage périphérique", qty: 20, unit: "ml", price: 18 },
        ],
        supplies: ["Béton C25/30", "Blocs béton", "Treillis", "Fers à béton", "Mortier", "Film polyéthylène"],
        jargon: ["empierrement", "hourdis", "chape", "ferraillage", "linteau"],
        vat: "21 % (construction neuve)",
      },
      {
        id: "menuisier",
        name: "Menuisier",
        voice: "Pour Mme Claes à Bruxelles, pose de 3 châssis PVC double vitrage 120 sur 135, démontage des anciens châssis en bois, habillage et joints.",
        lines: [
          { label: "Châssis PVC 2 ouvrants 120×135 Uw 1,3", qty: 3, unit: "u", price: 540 },
          { label: "Démontage châssis bois existants", qty: 3, unit: "u", price: 65 },
          { label: "Habillage + couvre-joints PVC", qty: 3, unit: "u", price: 48 },
          { label: "Mastic + mousse PU + compribande", qty: 1, unit: "lot", price: 45 },
        ],
        supplies: ["Châssis PVC / alu", "Compribande", "Mousse PU", "Couvre-joints", "Vis", "Quincaillerie"],
        jargon: ["châssis", "dormant", "ouvrant", "Uw", "compribande"],
        vat: "6 % (logement privé de plus de 10 ans)",
      },
      {
        id: "paysagiste",
        name: "Paysagiste / jardinier",
        voice: "Pour la villa Lambert à Waterloo, 120 m² de gazon en rouleaux, 8 m³ de terre arable, 25 m² de pavés de terrasse et l'entretien mensuel des haies.",
        lines: [
          { label: "Terre arable criblée livrée et étalée", qty: 8, unit: "m³", price: 48 },
          { label: "Gazon en rouleaux posé", qty: 120, unit: "m²", price: 11.5 },
          { label: "Pavés de terrasse posés sur empierrement", qty: 25, unit: "m²", price: 78 },
          { label: "Taille des haies (entretien mensuel)", qty: 3, unit: "h", price: 45 },
        ],
        supplies: ["Terre arable", "Gazon en rouleaux", "Paillis", "Pavés et bordures", "Empierrement", "Végétaux"],
        jargon: ["empierrement", "paillage", "scarification", "bordure", "drainage"],
        vat: "21 % (jardin : exclu du 6 %)",
      },
    ] as Trade[],
  },
  features: {
    eyebrow: "Fonctionnalités",
    title: "Tout le bureau, dans votre poche.",
    subtitle: "Pensé pour le chantier et pour les règles belges. Un seul abonnement, tout inclus.",
    voice: {
      title: "Dictée vocale → devis",
      desc: "Parlez comme sur le chantier. Biltov reconnaît quantités, unités et prix, retrouve les articles de votre catalogue et prépare un devis PDF prêt à signer.",
      listening: "Écoute…",
      thinking: "Chiffrage…",
      ready: "PDF prêt",
      transcript: "« Salle de bain chez Durand, faïence 18 m², pose d'un receveur extra-plat, 2 jours de main-d'œuvre »",
      pdfLines: ["Faïence murale 30×60 — 18 m²", "Receveur extra-plat 90×120", "Main-d'œuvre carreleur — 2 j"],
      quote: "DEVIS D-2026-0142",
    },
    channels: {
      title: "Envoi e-mail, WhatsApp, SMS",
      desc: "Le message part prêt, dans la langue du client, avec le PDF. Entre entreprises, la facture est générée au format Peppol.",
      email: "E-mail",
      whatsapp: "WhatsApp",
      sms: "SMS",
      send: "Envoyer le devis",
      sending: "Envoi…",
      delivered: "Envoyé",
      reset: "Recommencer",
      none: "Activez au moins un canal",
    },
    reminders: {
      title: "Relances selon les règles belges",
      desc: "Biltov prépare chaque relance au bon moment : Livre XIX pour les particuliers (1er rappel gratuit, 14 jours de délai), loi du 2 août 2002 pour les professionnels.",
      steps: [
        { day: "1", title: "1er rappel (gratuit)", msg: "Bonjour M. Durand, sauf erreur, la facture F-2026-0088 (1 240 €) n'est pas encore réglée. Merci de la payer dans les 14 jours, sans frais. Communication : +++090/9337/55493+++" },
        { day: "2", title: "Relance", msg: "Bonjour M. Durand, malgré notre rappel, la facture F-2026-0088 reste impayée. Des frais et intérêts sont désormais dus, conformément au Livre XIX du Code de droit économique." },
        { day: "3", title: "Mise en demeure", msg: "Mise en demeure de payer la facture F-2026-0088, frais et intérêts compris, sous 8 jours. À défaut, le dossier sera transmis pour recouvrement." },
      ],
      paid: "Payé — relances arrêtées",
      markPaid: "Simuler un paiement",
    },
    photo: {
      title: "Photos & marge du chantier",
      desc: "Photos avant/après horodatées dans le dossier chantier. Photographiez vos tickets : Biltov lit le montant et calcule la marge.",
      before: "Avant",
      after: "Après",
      scan: "Scanner un ticket",
      scanning: "Lecture…",
      receipt: "Ticket négoce",
      items: [
        { label: "Colle carrelage C2 × 4", value: 86.4 },
        { label: "Croisillons 3 mm", value: 7.9 },
        { label: "Joint gris 5 kg", value: 18.5 },
      ],
      billed: "Facturé au client",
      costs: "Achats",
      margin: "Marge du chantier",
    },
    brand: {
      title: "Vos documents, à votre image",
      desc: "Votre logo, vos couleurs, votre IBAN et votre numéro BCE. La TVA belge est calculée ligne par ligne.",
      upload: "Importer votre logo",
      color: "Couleur",
      country: "Taux de TVA",
      iban: "IBAN",
      company: "Dupont Rénovation SRL",
      preview: "Aperçu PDF",
      subtotal: "Total HTVA",
      vat: "TVA",
      total: "Total TVAC",
    },
  },
  demo: {
    eyebrow: "Démo en direct",
    title: "Dites-le. Regardez le devis se remplir.",
    subtitle: "Choisissez une phrase exemple, tapez la vôtre ou utilisez votre micro : le devis se construit ligne par ligne.",
    examples: [
      "Pour Mme Martin, pose de 24 m² de parquet chêne à 45 euros, 12 ml de plinthes à 9 euros et 6 heures de main-d'œuvre à 50 euros",
      "Pour M. Lambert, 3 prises électriques à 38 euros, un coffret 2 rangées à 180 euros et 4 heures de main-d'œuvre à 55 euros",
      "Pour Horizon SRL, peinture de 60 m² de murs à 22 euros et 18 m² de plafond à 25 euros",
    ],
    placeholder: "Ex. : Pour M. Dubois, 10 m² de carrelage à 40 euros et 5 heures à 50 euros",
    simulate: "Lancer la dictée",
    mic: "Dicter au micro",
    stop: "Arrêter",
    micUnsupported: "Micro non disponible dans ce navigateur — utilisez un exemple.",
    listening: "Biltov écoute…",
    reset: "Effacer",
    live: "Transcription en direct",
    pdf: {
      quote: "DEVIS",
      number: "D-2026-",
      client: "Client",
      clientUnknown: "Client à préciser",
      date: "Date",
      designation: "Désignation",
      qty: "Qté",
      unitPrice: "PU HTVA",
      total: "Total HTVA",
      subtotal: "Total HTVA",
      vat: "TVA 6 %",
      vatRate: 6,
      totalTTC: "Total TVAC",
      validity: "Devis valable 30 jours · « Lu et approuvé » :",
      empty: "Les lignes apparaîtront ici pendant la dictée…",
      labour: "Main-d'œuvre",
    },
  },
  roi: {
    eyebrow: "Calculateur",
    title: "Combien de temps récupérez-vous ?",
    subtitle: "Ajustez les curseurs à votre activité. Le calcul est volontairement prudent.",
    quotes: "Devis et factures par mois",
    minutes: "Temps actuel par document (min)",
    rate: "Votre taux horaire (€)",
    unpaid: "Impayés en attente par mois (€)",
    hoursSaved: "Heures récupérées / mois",
    moneySaved: "Valeur du temps gagné",
    recovered: "Trésorerie récupérée plus vite",
    roi: "Retour sur investissement",
    perMonth: "/ mois",
    note: "Hypothèses : 3 min par document avec Biltov, 30 % des impayés encaissés plus tôt grâce aux relances. Estimation, pas une promesse.",
    cta: "Récupérer ce temps",
  },
  pricing: {
    eyebrow: "Tarifs",
    title: "Trois forfaits, des devis illimités partout.",
    subtitle: "Le prix suit la taille de votre entreprise, pas le nombre de devis. Prix hors TVA, sans engagement.",
    monthly: "Mensuel",
    yearly: "Annuel",
    save: "2 mois offerts",
    perMonth: "€ HTVA / mois",
    billedYearly: "soit {p} € HTVA facturés une fois par an",
    billedMonthly: "Sans engagement, résiliable à tout moment",
    vatNote: "TVA belge de 21 % en sus.",
    popular: "Le plus choisi",
    cta: "Essai gratuit de 5 jours",
    guarantee: "5 jours avec toutes les fonctionnalités du Max · Sans carte bancaire · Ensuite, vous choisissez votre forfait",
    unlimitedQuotes: "Devis illimités",
    invoices: "{n} factures Peppol envoyées / mois",
    overage: "puis {p} € HTVA par facture en plus",
    users1: "1 utilisateur",
    usersN: "Jusqu'à {n} utilisateurs",
    usersInf: "Utilisateurs illimités",
    plans: {
      starter: {
        audience: "Artisan seul",
        points: [
          "Devis, factures et export PDF",
          "TVA belge, Peppol, relances",
          "Clients, chantiers, catalogue, banque",
        ],
      },
      pro: {
        audience: "Petite équipe",
        points: [
          "Tout le Starter",
          "Stocks, achats, flotte, outils",
          "Agenda, contrats, modules complémentaires",
        ],
      },
      max: {
        audience: "Entreprise structurée",
        points: [
          "Tout le Pro",
          "Employés, pointage, espace ouvriers",
          "Rôles personnalisés, sous-traitance ligne par ligne",
          "Gantt, intempéries, analyse matériaux, mode 3D",
        ],
      },
    },
    compareTitle: "Comparer les forfaits",
    compareLink: "Comparer les forfaits en détail",
    rows: {
      price: "Prix HTVA / mois",
      invoices: "Factures Peppol envoyées / mois",
      overage: "Au-delà du quota",
      overageBlocked: "Passage au forfait supérieur",
      users: "Utilisateurs",
      quotes: "Devis",
      unlimited: "Illimités",
      docs: "Devis, factures et export PDF",
      crm: "Clients, chantiers et catalogue",
      money: "Argent à recevoir, banque et exports comptables",
      stock: "Stocks",
      ops: "Achats, flotte, outils et contrats",
      planning: "Agenda et modules complémentaires",
      team: "Employés, pointage et espace ouvriers",
      roles: "Rôles personnalisés (super admin)",
      subcontract: "Sous-traitance ligne par ligne",
      gantt: "Gantt et calendrier des intempéries",
      profit: "Rentabilité et analyse matériaux",
      mode3d: "Mode 3D",
    },
    faqTitle: "Questions sur les forfaits",
    faq: [
      {
        q: "Les devis sont-ils vraiment illimités ?",
        a: "Oui, dans tous les forfaits. Seules les factures envoyées via Peppol sont comptées : c'est le seul envoi qui a un coût pour nous.",
      },
      {
        q: "Que se passe-t-il si j'atteins mon quota de factures ?",
        a: "Une alerte apparaît à 80 % puis à 100 %. En Starter et en Pro, l'envoi Peppol est bloqué jusqu'à la période suivante, ou vous passez au forfait supérieur en un clic. En Max, chaque facture en plus est facturée en fin de période.",
      },
      {
        q: "Puis-je changer de forfait ?",
        a: "À tout moment, au prorata. Si vous descendez, Biltov vous prévient d'abord de ce qui dépasse le nouveau forfait (utilisateurs, modules). Aucune donnée n'est jamais supprimée.",
      },
      {
        q: "Et à la fin de l'essai ?",
        a: "Vos données restent consultables en lecture seule jusqu'au choix d'un forfait. Rien n'est effacé.",
      },
      {
        q: "Comment se passe le paiement ?",
        a: "Par carte, Bancontact ou domiciliation, via Stripe. La TVA belge de 21 % est ajoutée et vous recevez une facture chaque mois (ou chaque année).",
      },
    ],
  },
  faq: {
    eyebrow: "FAQ",
    title: "Questions fréquentes",
    items: [
      { q: "La dictée fonctionne-t-elle sur un chantier bruyant ?", a: "La reconnaissance vocale est celle de votre navigateur (Chrome, Edge, Safari). Dans le bruit, parlez près du téléphone. Vous pouvez aussi taper la phrase et corriger chaque ligne avant l'envoi." },
      { q: "Mes devis et factures respectent-ils les règles belges ?", a: "Biltov applique les mentions obligatoires, une numérotation continue, le taux de 6, 12 ou 21 % selon la nature des travaux et l'âge du logement, l'autoliquidation pour les clients assujettis et la communication structurée. Les taux et seuils utilisés sont datés et sourcés dans les paramètres : faites-les valider par votre comptable." },
      { q: "Et Peppol, obligatoire entre entreprises ?", a: "Biltov génère la facture au format Peppol BIS 3.0 (UBL). Pour l'instant, vous déposez ce fichier chez votre prestataire Peppol ; la transmission directe depuis Biltov arrivera avec le serveur." },
      { q: "Faut-il une carte bancaire pour l'essai ?", a: "Non. Créez simplement votre compte (e-mail et mot de passe) et utilisez tout Biltov gratuitement pendant 5 jours, sans carte. Ensuite, vous choisissez le forfait Starter, Pro ou Max (voir les tarifs) ; sans forfait, vos données restent consultables en lecture seule." },
      { q: "Mes clients doivent-ils installer quelque chose ?", a: "Non. Ils reçoivent le PDF par e-mail, WhatsApp ou SMS. La signature se fait sur votre téléphone ou votre tablette, sur le chantier." },
      { q: "Puis-je importer mes clients et mon catalogue ?", a: "Oui, par fichier Excel ou CSV : vous associez les colonnes, Biltov simule l'import et signale les erreurs avant d'enregistrer. Le fichier de prix de votre négoce se réimporte pour mettre vos prix à jour." },
      { q: "Où sont stockées mes données ?", a: "Aujourd'hui, sur votre appareil (dans le navigateur), avec un mot de passe chiffré. Exportez régulièrement une sauvegarde complète depuis les paramètres. La synchronisation entre appareils arrivera avec le serveur." },
      { q: "Et si je veux arrêter ?", a: "Vous résiliez à tout moment. Vous pouvez exporter vos données : sauvegarde complète et journaux comptables en CSV ou Excel." },
    ],
  },
  footer: {
    tagline: "L'assistant vocal et de facturation des artisans du bâtiment en Belgique.",
    product: "Produit",
    company: "Entreprise",
    legal: "Légal",
    links: {
      product: ["Fonctionnalités", "Métiers", "Tarif", "Calculateur", "Démo"],
      company: ["À propos", "Contact"],
      legal: ["Mentions légales", "Conditions générales", "Politique de confidentialité", "Cookies"],
    },
    compliance: ["TVA belge", "Peppol BIS 3.0", "FR · NL · DE"],
    rights: "Tous droits réservés.",
    made: "Conçu pour les artisans du bâtiment en Belgique.",
  },
};

export type Dict = typeof fr;
