import type { Dict, Trade } from "./fr";

export const nl: Dict = {
  meta: {
    title: "Biltov — De spraak- en facturatieassistent voor bouwvakmensen in België",
    description: "Dicteer uw offertes op de werf in het Nederlands, Frans of Duits. Biltov past de Belgische btw toe, maakt uw Peppol-facturen op en helpt u betaald te worden.",
  },
  nav: {
    features: "Functies",
    trades: "Vakken",
    pricing: "Prijs",
    roi: "Rekenmodule",
    cta: "1 dag gratis proberen",
    dashboard: "Mijn ruimte",
    language: "Taal",
    openMenu: "Menu openen",
    closeMenu: "Menu sluiten",
  },
  hero: {
    badge: "Voor vakmensen in België · NL · FR · DE",
    titleA: "Leg de pen neer.",
    titleHighlight: "Dicteer.",
    titleB: "Biltov doet het papierwerk.",
    subtitle:
      "Dicteer de offerte op de werf: Biltov vindt uw prijzen terug, past het juiste Belgische btw-tarief toe, zet ze in uw huisstijl en helpt u ze te laten ondertekenen, te factureren en te innen.",
    ctaPrimary: "Dicteren testen",
    ctaSecondary: "Demo bekijken",
    reassurance: ["Belgische btw 6 / 12 / 21 % en verlegging", "Peppol BIS 3.0-facturen", "1 dag gratis proberen"],
    stats: [
      { value: "30 s", label: "om een offerte te dicteren" },
      { value: "3", label: "talen: NL, FR, DE" },
      { value: "+++", label: "gestructureerde mededeling op elke factuur" },
    ],
    canvasHint: "Beweeg de muis om rond de werf te draaien",
    scroll: "Scrollen",
  },
  trades: {
    eyebrow: "Uw vak",
    title: "Biltov spreekt uw vak.",
    subtitle: "Kies uw vak: de woordenschat en de startcatalogus passen zich aan. Uw prijzen blijven de uwe.",
    labels: {
      dictation: "U dicteert",
      generated: "Biltov maakt op",
      supplies: "Startcatalogus",
      jargon: "Begrepen vakjargon",
      vat: "Toegepaste btw",
      total: "Totaal excl. btw",
      designation: "Omschrijving",
      qty: "Aant.",
      price: "EP excl. btw",
    },
    list: [
      {
        id: "plombier",
        name: "Loodgieter-verwarmingsinstallateur",
        voice: "Voor mevrouw Peeters in Gent, vervanging van de elektrische boiler 200 liter, veiligheidsgroep, meerlagige koppelingen en 3 uur werk.",
        lines: [
          { label: "Elektrische boiler 200 L verticaal", qty: 1, unit: "u", price: 489 },
          { label: "Veiligheidsgroep + sifon", qty: 1, unit: "u", price: 42 },
          { label: "Meerlagige koppelingen Ø16 + beugels", qty: 1, unit: "lot", price: 36 },
          { label: "Werkuren loodgieter", qty: 3, unit: "h", price: 55 },
        ],
        supplies: ["Meerlagige buis Ø16 / Ø20", "Messing koppelingen", "Boilers", "Mengkranen", "Sifons", "Kwartslagkranen"],
        jargon: ["boiler", "veiligheidsgroep", "meerlagige buis", "terugslagklep", "expansievat"],
        vat: "6 % (privéwoning ouder dan 10 jaar)",
      },
      {
        id: "electricien",
        name: "Elektricien",
        voice: "Voor meneer Janssens in Hasselt, vervanging van de verdeelkast, 2 verliesstroomschakelaars 30 milliampère, 12 automaten, 6 stopcontacten en 5 uur werk.",
        lines: [
          { label: "Verdeelkast 3 rijen", qty: 1, unit: "u", price: 128 },
          { label: "Verliesstroomschakelaar 40 A 30 mA type A", qty: 2, unit: "u", price: 74 },
          { label: "Automaat 2-polig 16 A", qty: 12, unit: "u", price: 11.5 },
          { label: "Inbouwstopcontact + plaatsing", qty: 6, unit: "u", price: 38 },
        ],
        supplies: ["Automaten", "Verliesstroomschakelaars 30 mA", "Buizen", "Kabel XVB / VOB", "Inbouwdozen", "Kammen"],
        jargon: ["AREI", "keuring", "verliesstroomschakelaar", "verdeelkast", "eendraadschema"],
        vat: "6 % (privéwoning ouder dan 10 jaar)",
      },
      {
        id: "peintre",
        name: "Schilder",
        voice: "Voor de familie Wouters in Leuven, afwassen, plamuren, grondlaag en twee lagen witte latex op 38 m² muren, plafond van 14 m² in mat.",
        lines: [
          { label: "Afwassen + plamuren + schuren muren", qty: 38, unit: "m²", price: 6 },
          { label: "Acrylgrondlaag", qty: 38, unit: "m²", price: 4.5 },
          { label: "Witte latex 2 lagen", qty: 38, unit: "m²", price: 14 },
          { label: "Plafond matte verf 2 lagen", qty: 14, unit: "m²", price: 17 },
        ],
        supplies: ["Latex / acryl", "Egaliseerplamuur", "Voegband", "Rollers", "Afdekzeilen", "Afplakpapier"],
        jargon: ["latex", "fixeermiddel", "plamuren", "tussenschuren", "diepmat"],
        vat: "6 % (privéwoning ouder dan 10 jaar)",
      },
      {
        id: "macon",
        name: "Metselaar",
        voice: "Voor meneer Claes in Mechelen, terrasplaat van 25 m² in een nieuwbouw, 12 centimeter, wapeningsnet, steenslag van 20 cm en bekisting.",
        lines: [
          { label: "Grondwerk + steenslag 20 cm", qty: 25, unit: "m²", price: 28 },
          { label: "Wapeningsnet", qty: 25, unit: "m²", price: 7.5 },
          { label: "Beton C25/30 dikte 12 cm gestort", qty: 3, unit: "m³", price: 165 },
          { label: "Randbekisting", qty: 20, unit: "ml", price: 18 },
        ],
        supplies: ["Beton C25/30", "Betonblokken", "Wapeningsnetten", "Betonstaal", "Mortel", "Polyethyleenfolie"],
        jargon: ["steenslag", "welfsels", "chape", "wapening", "latei"],
        vat: "21 % (nieuwbouw)",
      },
      {
        id: "menuisier",
        name: "Schrijnwerker",
        voice: "Voor mevrouw Maes in Antwerpen, plaatsing van 3 PVC-ramen dubbel glas 120 op 135, demontage van de oude houten ramen, afwerking en voegen.",
        lines: [
          { label: "PVC-raam 2 vleugels 120×135 Uw 1,3", qty: 3, unit: "u", price: 540 },
          { label: "Demontage bestaande houten ramen", qty: 3, unit: "u", price: 65 },
          { label: "Afwerking + PVC-afdeklijsten", qty: 3, unit: "u", price: 48 },
          { label: "Kit + PU-schuim + compriband", qty: 1, unit: "lot", price: 45 },
        ],
        supplies: ["PVC- / aluramen", "Compriband", "PU-schuim", "Afdeklijsten", "Schroeven", "Beslag"],
        jargon: ["raam", "kader", "vleugel", "Uw", "compriband"],
        vat: "6 % (privéwoning ouder dan 10 jaar)",
      },
    ] as Trade[],
  },
  features: {
    eyebrow: "Functies",
    title: "Het hele kantoor in uw broekzak.",
    subtitle: "Ontworpen voor de werf en voor de Belgische regels. Eén abonnement, alles inbegrepen.",
    voice: {
      title: "Dicteren → offerte",
      desc: "Spreek zoals op de werf. Biltov herkent hoeveelheden, eenheden en prijzen, vindt de artikelen uit uw catalogus en maakt een pdf-offerte klaar om te ondertekenen.",
      listening: "Luistert…",
      thinking: "Berekenen…",
      ready: "Pdf klaar",
      transcript: "« Badkamer bij Wouters, 18 m² faience, plaatsing van een extra platte douchebak, 2 dagen werk »",
      pdfLines: ["Wandtegels 30×60 — 18 m²", "Extra platte douchebak 90×120", "Werkuren tegelzetter — 2 d"],
      quote: "OFFERTE D-2026-0142",
    },
    channels: {
      title: "Verzenden via e-mail, WhatsApp, sms",
      desc: "Het bericht vertrekt klaar, in de taal van de klant, met de pdf. Tussen ondernemingen wordt de factuur in Peppol-formaat opgemaakt.",
      email: "E-mail",
      whatsapp: "WhatsApp",
      sms: "Sms",
      send: "Offerte versturen",
      sending: "Verzenden…",
      delivered: "Verzonden",
      reset: "Opnieuw",
      none: "Activeer minstens één kanaal",
    },
    reminders: {
      title: "Herinneringen volgens de Belgische regels",
      desc: "Biltov bereidt elke herinnering op het juiste moment voor: Boek XIX voor particulieren (1e herinnering gratis, 14 dagen termijn), wet van 2 augustus 2002 voor professionelen.",
      steps: [
        { day: "1", title: "1e herinnering (gratis)", msg: "Beste meneer Wouters, tenzij vergissing is factuur F-2026-0088 (1 240 €) nog niet betaald. Gelieve ze binnen 14 dagen te betalen, zonder kosten. Mededeling: +++090/9337/55493+++" },
        { day: "2", title: "Aanmaning", msg: "Beste meneer Wouters, ondanks onze herinnering blijft factuur F-2026-0088 onbetaald. Er zijn nu kosten en interesten verschuldigd, overeenkomstig Boek XIX van het Wetboek van economisch recht." },
        { day: "3", title: "Ingebrekestelling", msg: "Ingebrekestelling om factuur F-2026-0088, kosten en interesten inbegrepen, binnen 8 dagen te betalen. Zo niet wordt het dossier overgedragen voor invordering." },
      ],
      paid: "Betaald — herinneringen gestopt",
      markPaid: "Betaling simuleren",
    },
    photo: {
      title: "Foto's & marge van de werf",
      desc: "Foto's voor/na met tijdstempel in het werfdossier. Fotografeer uw tickets: Biltov leest het bedrag en berekent de marge.",
      before: "Voor",
      after: "Na",
      scan: "Ticket scannen",
      scanning: "Lezen…",
      receipt: "Ticket groothandel",
      items: [
        { label: "Tegellijm C2 × 4", value: 86.4 },
        { label: "Tegelkruisjes 3 mm", value: 7.9 },
        { label: "Voegmiddel grijs 5 kg", value: 18.5 },
      ],
      billed: "Gefactureerd aan de klant",
      costs: "Aankopen",
      margin: "Marge van de werf",
    },
    brand: {
      title: "Uw documenten, in uw stijl",
      desc: "Uw logo, uw kleuren, uw IBAN en uw ondernemingsnummer. De Belgische btw wordt per regel berekend.",
      upload: "Uw logo importeren",
      color: "Kleur",
      country: "Btw-tarief",
      iban: "IBAN",
      company: "Peeters Renovatie BV",
      preview: "Pdf-voorbeeld",
      subtotal: "Totaal excl. btw",
      vat: "Btw",
      total: "Totaal incl. btw",
    },
  },
  demo: {
    eyebrow: "Live demo",
    title: "Zeg het. Kijk hoe de offerte zich vult.",
    subtitle: "Kies een voorbeeldzin, typ de uwe of gebruik uw microfoon: de offerte wordt regel per regel opgebouwd.",
    examples: [
      "Voor mevrouw Martens, 24 m² eiken parket aan 45 euro, 12 lm plinten aan 9 euro en 6 uur werk aan 50 euro",
      "Voor meneer Lambrechts, 3 stopcontacten aan 38 euro, een verdeelkast aan 180 euro en 4 uur werk aan 55 euro",
      "Voor Horizon BV, 60 m² muren schilderen aan 22 euro en 18 m² plafond aan 25 euro",
    ],
    placeholder: "Bv.: Voor meneer Dubois, 10 m² tegels aan 40 euro en 5 uur aan 50 euro",
    simulate: "Dicteren starten",
    mic: "Dicteren met microfoon",
    stop: "Stoppen",
    micUnsupported: "Microfoon niet beschikbaar in deze browser — gebruik een voorbeeld.",
    listening: "Biltov luistert…",
    reset: "Wissen",
    live: "Live transcriptie",
    pdf: {
      quote: "OFFERTE",
      number: "D-2026-",
      client: "Klant",
      clientUnknown: "Klant te bepalen",
      date: "Datum",
      designation: "Omschrijving",
      qty: "Aant.",
      unitPrice: "EP excl. btw",
      total: "Totaal excl. btw",
      subtotal: "Totaal excl. btw",
      vat: "Btw 6 %",
      vatRate: 6,
      totalTTC: "Totaal incl. btw",
      validity: "Offerte 30 dagen geldig · « Gelezen en goedgekeurd »:",
      empty: "De regels verschijnen hier tijdens het dicteren…",
      labour: "Werkuren",
    },
  },
  roi: {
    eyebrow: "Rekenmodule",
    title: "Hoeveel tijd wint u terug?",
    subtitle: "Stel de schuifregelaars in op uw activiteit. De berekening is bewust voorzichtig.",
    quotes: "Offertes en facturen per maand",
    minutes: "Huidige tijd per document (min)",
    rate: "Uw uurtarief (€)",
    unpaid: "Openstaande onbetaalde facturen per maand (€)",
    hoursSaved: "Teruggewonnen uren / maand",
    moneySaved: "Waarde van de gewonnen tijd",
    recovered: "Sneller geïnde liquiditeit",
    roi: "Rendement",
    perMonth: "/ maand",
    note: "Aannames: 3 min per document met Biltov, 30 % van de onbetaalde facturen sneller geïnd dankzij de herinneringen. Een schatting, geen belofte.",
    cta: "Die tijd terugwinnen",
  },
  pricing: {
    eyebrow: "Eén tarief",
    title: "Eén prijs. Alles inbegrepen.",
    subtitle: "Geen niveaus, geen verborgen opties, geen limiet op offertes. Alle functies voor iedereen.",
    monthly: "Maandelijks",
    yearly: "Jaarlijks",
    save: "-20 %",
    badge: "Alles inbegrepen · Zonder verbintenis",
    plan: "Biltov Pro",
    perMonth: "€ excl. btw / maand",
    billedYearly: "of 768 € excl. btw, eenmaal per jaar gefactureerd",
    billedMonthly: "Op elk moment opzegbaar",
    features: [
      "Onbeperkt dicteren (NL / FR / DE)",
      "Offertes, voorschotten, vorderingsstaten, facturen en creditnota's",
      "Belgische btw: 6 / 12 / 21 %, verlegging, vrijstellingsregeling",
      "Peppol BIS 3.0-facturen (UBL-bestand) voor uw professionele klanten",
      "Gestructureerde mededeling +++ en QR-code voor overschrijving",
      "Herinneringen conform Boek XIX en de wet van 2002",
      "Catalogus en Excel-import van leveranciersprijzen",
      "Planning, prikklok, arbeidersruimte, foto's voor / na",
      "Aankopen, onderaanneming (inhoudingsplicht), voorraad",
    ],
    cta: "Gratis proefdag starten",
    guarantee: "1 dag gratis · Kaart vereist · Daarna automatische betaling · Op elk moment opzegbaar",
    roiLine: "Terugverdiend vanaf 1,5 uur bespaard papierwerk per maand.",
  },
  faq: {
    eyebrow: "FAQ",
    title: "Veelgestelde vragen",
    items: [
      { q: "Werkt dicteren op een lawaaierige werf?", a: "De spraakherkenning is die van uw browser (Chrome, Edge, Safari). Spreek bij lawaai dicht bij de telefoon. U kunt de zin ook typen en elke regel verbeteren vóór het verzenden." },
      { q: "Respecteren mijn offertes en facturen de Belgische regels?", a: "Biltov past de verplichte vermeldingen toe, een doorlopende nummering, het tarief van 6, 12 of 21 % volgens de aard van de werken en de ouderdom van de woning, de verlegging voor btw-plichtige klanten en de gestructureerde mededeling. De gebruikte tarieven en drempels staan gedateerd en met bron in de instellingen: laat ze valideren door uw boekhouder." },
      { q: "En Peppol, verplicht tussen ondernemingen?", a: "Biltov maakt de factuur op in Peppol BIS 3.0-formaat (UBL). Voorlopig dient u dat bestand in bij uw Peppol-dienstverlener; rechtstreekse verzending vanuit Biltov komt met de server." },
      { q: "Is een bankkaart nodig voor de proefperiode?", a: "Ja. U registreert uw kaart bij de start en gebruikt Biltov 1 dag gratis. Zonder opzegging vóór het einde van de proefperiode wordt het abonnement daarna automatisch maandelijks (of jaarlijks) afgeschreven." },
      { q: "Moeten mijn klanten iets installeren?", a: "Nee. Ze ontvangen de pdf via e-mail, WhatsApp of sms. Ondertekenen gebeurt op uw telefoon of tablet, op de werf." },
      { q: "Kan ik mijn klanten en catalogus importeren?", a: "Ja, via een Excel- of CSV-bestand: u koppelt de kolommen, Biltov simuleert de import en meldt fouten vóór het opslaan. Het prijsbestand van uw groothandel kunt u opnieuw importeren om uw prijzen bij te werken." },
      { q: "Waar worden mijn gegevens bewaard?", a: "Vandaag op uw toestel (in de browser), met een versleuteld wachtwoord. Exporteer regelmatig een volledige back-up via de instellingen. Synchronisatie tussen toestellen komt met de server." },
      { q: "En als ik wil stoppen?", a: "U zegt op elk moment op. U kunt uw gegevens exporteren: volledige back-up en boekhoudkundige dagboeken in CSV of Excel." },
    ],
  },
  footer: {
    tagline: "De spraak- en facturatieassistent voor bouwvakmensen in België.",
    product: "Product",
    company: "Onderneming",
    legal: "Juridisch",
    links: {
      product: ["Functies", "Vakken", "Prijs", "Rekenmodule", "Demo"],
      company: ["Over ons", "Contact"],
      legal: ["Wettelijke vermeldingen", "Algemene voorwaarden", "Privacybeleid", "Cookies"],
    },
    compliance: ["Belgische btw", "Peppol BIS 3.0", "NL · FR · DE"],
    rights: "Alle rechten voorbehouden.",
    made: "Ontworpen voor bouwvakmensen in België.",
  },
};
