// Libellés des documents envoyés au client, en FR / NL / DE.

import type { Lang } from "./types";

const T = {
  quote: ["DEVIS", "OFFERTE", "ANGEBOT"],
  invoice: ["FACTURE", "FACTUUR", "RECHNUNG"],
  deposit: ["FACTURE D'ACOMPTE", "VOORSCHOTFACTUUR", "ANZAHLUNGSRECHNUNG"],
  situation: ["ÉTAT D'AVANCEMENT", "VORDERINGSSTAAT", "ABSCHLAGSRECHNUNG"],
  final: ["FACTURE FINALE", "EINDFACTUUR", "SCHLUSSRECHNUNG"],
  credit: ["NOTE DE CRÉDIT", "CREDITNOTA", "GUTSCHRIFT"],
  proforma: ["FACTURE PRO FORMA", "PROFORMAFACTUUR", "PROFORMARECHNUNG"],
  reminder: ["RAPPEL DE PAIEMENT", "BETALINGSHERINNERING", "ZAHLUNGSERINNERUNG"],
  number: ["N°", "Nr.", "Nr."],
  date: ["Date", "Datum", "Datum"],
  validUntil: ["Valable jusqu'au", "Geldig tot", "Gültig bis"],
  workDate: ["Date de prestation", "Datum van prestatie", "Leistungsdatum"],
  dueDate: ["Échéance", "Vervaldatum", "Fällig am"],
  ref: ["Réf.", "Ref.", "Ref."],
  client: ["Client", "Klant", "Kunde"],
  site: ["Chantier", "Werf", "Baustelle"],
  vatNo: ["TVA", "Btw", "MwSt."],
  bce: ["BCE", "KBO", "ZDU"],
  designation: ["Désignation", "Omschrijving", "Bezeichnung"],
  qty: ["Qté", "Aantal", "Menge"],
  unit: ["Unité", "Eenheid", "Einheit"],
  unitPrice: ["PU HTVA", "EP excl. btw", "EP netto"],
  discount: ["Rem.", "Korting", "Rabatt"],
  vat: ["TVA", "Btw", "MwSt."],
  total: ["Total HTVA", "Totaal excl. btw", "Gesamt netto"],
  option: ["Option", "Optie", "Option"],
  notSelected: ["non retenue", "niet gekozen", "nicht gewählt"],
  subtotal: ["Total HTVA", "Totaal excl. btw", "Summe netto"],
  globalDiscount: ["Remise", "Korting", "Rabatt"],
  base: ["Base", "Maatstaf", "Bemessungsgrundlage"],
  vatAmount: ["Montant TVA", "Btw-bedrag", "MwSt.-Betrag"],
  totalTvac: ["Total TVAC", "Totaal incl. btw", "Gesamt brutto"],
  depositAsked: ["Acompte demandé", "Gevraagd voorschot", "Angeforderte Anzahlung"],
  retention: ["Retenue de garantie", "Waarborginhouding", "Garantieeinbehalt"],
  paid: ["Déjà payé", "Reeds betaald", "Bereits bezahlt"],
  toPay: ["À payer", "Te betalen", "Zu zahlen"],
  reverse: ["Autoliquidation", "Verlegging", "Reverse Charge"],
  franchise: ["Franchise", "Vrijstelling", "Befreiung"],
  exempt: ["Exonéré", "Vrijgesteld", "Befreit"],
  payment: ["Paiement", "Betaling", "Zahlung"],
  payTo: ["Virement sur", "Overschrijving op", "Überweisung auf"],
  communication: ["Communication structurée", "Gestructureerde mededeling", "Strukturierte Mitteilung"],
  scan: ["Scannez pour payer", "Scan om te betalen", "Zum Bezahlen scannen"],
  conditions: ["Conditions", "Voorwaarden", "Bedingungen"],
  mentions: ["Mentions", "Vermeldingen", "Hinweise"],
  agreement: ["BON POUR ACCORD", "VOOR AKKOORD", "EINVERSTANDEN"],
  agreementHint: ["Date et signature du client", "Datum en handtekening van de klant", "Datum und Unterschrift des Kunden"],
  signedBy: ["Signé par", "Ondertekend door", "Unterzeichnet von"],
  company: ["L'ENTREPRISE", "DE ONDERNEMING", "DAS UNTERNEHMEN"],
  validity: ["Devis valable jusqu'au {d}.", "Offerte geldig tot {d}.", "Angebot gültig bis {d}."],
  depositCond: ["Acompte de {p} % à la commande, solde à la réception des travaux.", "Voorschot van {p} % bij bestelling, saldo bij oplevering.", "Anzahlung von {p} % bei Auftrag, Rest bei Abnahme."],
  payBy: ["Paiement au plus tard le {d}, sur le compte {iban} avec la communication {c}.", "Betaling uiterlijk op {d}, op rekening {iban} met mededeling {c}.", "Zahlung spätestens am {d} auf das Konto {iban} mit der Mitteilung {c}."],
  lateB2b: [
    "En cas de retard de paiement, intérêts de retard au taux légal (loi du 2 août 2002) et indemnité forfaitaire de {f} €.",
    "Bij laattijdige betaling zijn nalatigheidsinteresten verschuldigd aan de wettelijke rentevoet (wet van 2 augustus 2002) en een forfaitaire vergoeding van {f} €.",
    "Bei Zahlungsverzug sind Verzugszinsen zum gesetzlichen Zinssatz (Gesetz vom 2. August 2002) und eine Pauschalentschädigung von {f} € geschuldet.",
  ],
  offPremises: [
    "Contrat conclu hors établissement : vous disposez d'un délai de rétractation de 14 jours (formulaire de rétractation joint).",
    "Overeenkomst buiten de verkoopruimte: u beschikt over een herroepingstermijn van 14 dagen (modelformulier bijgevoegd).",
    "Außerhalb von Geschäftsräumen geschlossener Vertrag: Sie haben ein Widerrufsrecht von 14 Tagen (Muster-Widerrufsformular anbei).",
  ],
  photoReport: ["RAPPORT PHOTO", "FOTORAPPORT", "FOTOBERICHT"],
  before: ["Avant", "Voor", "Vorher"],
  during: ["Pendant", "Tijdens", "Während"],
  after: ["Après", "Na", "Nachher"],
  visualTitle: ["AVANT / APRÈS", "VOOR / NA", "VORHER / NACHHER"],
  visualBefore: ["Avant : situation actuelle", "Voor: huidige toestand", "Vorher: aktueller Zustand"],
  visualAfter: ["Après : visualisation du résultat", "Na: visualisatie van het resultaat", "Nachher: Visualisierung des Ergebnisses"],
  visualNote: [
    "Visualisation indicative et non contractuelle : seul le descriptif du devis engage les parties.",
    "Indicatieve en niet-contractuele visualisatie: enkel de beschrijving in de offerte verbindt de partijen.",
    "Unverbindliche Visualisierung: Nur die Leistungsbeschreibung des Angebots ist verbindlich.",
  ],
  intervention: ["BON D'INTERVENTION", "INTERVENTIEBON", "EINSATZBERICHT"],
  demo: ["DÉMONSTRATION", "DEMONSTRATIE", "DEMONSTRATION"],
} as const;

const IDX: Record<Lang, number> = { fr: 0, nl: 1, de: 2 };
export type DocKey = keyof typeof T;
export const dt = (lang: Lang, key: DocKey, vars: Record<string, string | number> = {}) => T[key][IDX[lang]].replace(/\{(\w+)\}/g, (_, v) => String(vars[v] ?? ""));
export const LOCALE: Record<Lang, string> = { fr: "fr-BE", nl: "nl-BE", de: "de-BE" };
export const fmtDate = (iso: string, lang: Lang = "fr") => (iso ? new Date(`${iso.slice(0, 10)}T00:00:00`).toLocaleDateString(LOCALE[lang]) : "—");
